import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'hi' | 'pa' | 'mr' | 'ta' | 'te' | 'bn' | 'gu';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    appName: "CropWise AI",
    login: "Login",
    logout: "Logout",
    language: "Language",
    
    // Hero Section
    aiBadge: "AI-Powered Agriculture",
    heroTitle: "Smart Farming Starts Here",
    heroSubtitle: "Get AI-powered crop recommendations tailored to your soil, climate, and resources",
    getStarted: "Get Started",
    learnMore: "Learn More",
    cropTypes: "Crop Types",
    accuracy: "Accuracy",
    farmers: "Farmers",
    
    // Form
    formTitle: "Tell Us About Your Farm",
    formSubtitle: "Fill in your farm details to get personalized crop recommendations",
    soilType: "Soil Type",
    selectSoilType: "Select soil type",
    climate: "Climate",
    selectClimate: "Select climate",
    waterAvailability: "Water Availability",
    selectWaterAvailability: "Select water availability",
    farmSize: "Farm Size (acres)",
    enterFarmSize: "Enter farm size",
    season: "Growing Season",
    selectSeason: "Select season",
    getRecommendations: "Get Crop Recommendations",
    analyzing: "Analyzing...",
    
    // Image Upload
    orUploadImage: "Or Upload Photo",
    uploadImageDesc: "Upload photos of your soil, weather conditions, or crop to get AI recommendations",
    uploadPhoto: "Upload Photo",
    analyzeImage: "Analyze Image",
    analyzingImage: "Analyzing...",
    
    // Soil types
    clay: "Clay",
    sandy: "Sandy",
    loamy: "Loamy",
    silt: "Silt",
    peat: "Peat",
    chalky: "Chalky",
    
    // Climate
    tropical: "Tropical",
    subtropical: "Subtropical",
    temperate: "Temperate",
    arid: "Arid/Dry",
    semiarid: "Semi-Arid",
    
    // Water
    abundant: "Abundant (Irrigation)",
    moderate: "Moderate (Seasonal Rain)",
    limited: "Limited (Dry Region)",
    rainfed: "Rain-fed Only",
    
    // Seasons
    kharif: "Kharif (Monsoon)",
    rabi: "Rabi (Winter)",
    zaid: "Zaid (Summer)",
    yearround: "Year-round",
    
    // Results
    recommendedCrops: "Your Recommended Crops",
    basedOnConditions: "Based on your farm conditions, our AI recommends these crops for optimal growth and yield.",
    tryDifferent: "Try Different Conditions",
    downloadReport: "Download Report",
    
    // Crop Card
    water: "Water",
    sunlight: "Sunlight",
    growth: "Growth",
    yield: "Yield",
    growingTips: "Growing Tips",
    match: "Match",
    
    // Water levels
    waterLow: "Low",
    waterMedium: "Medium",
    waterHigh: "High",
    
    // Sunlight levels
    fullSun: "Full Sun",
    partialShade: "Partial Shade",
    shadeTolerant: "Shade Tolerant",
    
    // Yield levels
    yieldLow: "Low",
    yieldMedium: "Medium",
    yieldHigh: "High",
    
    // Crop names
    rice: "Rice",
    wheat: "Wheat",
    corn: "Corn (Maize)",
    soybean: "Soybean",
    cotton: "Cotton",
    millet: "Millet",
    potatoes: "Potatoes",
    tomatoes: "Tomatoes",
    sorghum: "Sorghum",
    sugarcane: "Sugarcane",
    
    // Crop descriptions
    riceDesc: "A staple grain crop that thrives in waterlogged conditions. Ideal for tropical and subtropical climates with abundant water.",
    wheatDesc: "A cool-season cereal grain that performs well in temperate climates with moderate water availability.",
    cornDesc: "A versatile crop suited for warm climates with moderate to good water supply. Excellent for various soil types.",
    soybeanDesc: "A nitrogen-fixing legume that enriches soil. Thrives in warm conditions with well-drained loamy soil.",
    cottonDesc: "A fiber crop that thrives in warm, semi-arid conditions. Tolerates various soil types but prefers deep, well-drained soil.",
    milletDesc: "A drought-tolerant grain ideal for arid regions with limited water. Grows well in sandy and poor soils.",
    potatoesDesc: "A tuber crop that excels in cool temperate climates with loose, well-drained loamy soil.",
    tomatoesDesc: "A warm-season vegetable requiring consistent water and nutrients. Best in loamy, well-drained soil.",
    sorghumDesc: "A drought-resistant cereal perfect for hot, dry climates. Versatile crop for grain, fodder, and biofuel.",
    sugarcaneDesc: "A tropical grass crop requiring abundant water and sunshine. Thrives in deep, fertile soil with good drainage.",
    
    // Crop tips
    riceTip1: "Maintain standing water of 2-5 cm during vegetative growth",
    riceTip2: "Apply nitrogen fertilizer in split doses",
    riceTip3: "Monitor for blast disease during humid conditions",
    wheatTip1: "Plant when soil temperature is between 10-15°C",
    wheatTip2: "Ensure good drainage to prevent root rot",
    wheatTip3: "Apply phosphorus at sowing for strong root development",
    cornTip1: "Plant when soil temperature reaches 16°C",
    cornTip2: "Space plants 20-30 cm apart in rows",
    cornTip3: "Critical irrigation during tasseling and silking stages",
    soybeanTip1: "Inoculate seeds with rhizobium for nitrogen fixation",
    soybeanTip2: "Avoid waterlogging during flowering",
    soybeanTip3: "Rotate with cereals for best soil health",
    cottonTip1: "Requires frost-free growing period of 180+ days",
    cottonTip2: "Monitor for bollworm and whitefly",
    cottonTip3: "Apply potassium for fiber quality improvement",
    milletTip1: "Highly drought tolerant once established",
    milletTip2: "Minimal fertilizer requirements",
    milletTip3: "Can serve as emergency fodder crop",
    potatoesTip1: "Hill soil around plants as they grow",
    potatoesTip2: "Keep tubers covered to prevent greening",
    potatoesTip3: "Rotate to prevent soil-borne diseases",
    tomatoesTip1: "Stake or cage plants for better air circulation",
    tomatoesTip2: "Mulch to maintain soil moisture",
    tomatoesTip3: "Prune suckers for larger fruits",
    sorghumTip1: "Deep root system enables drought survival",
    sorghumTip2: "Can ratoon for second harvest",
    sorghumTip3: "Control bird damage near maturity",
    sugarcaneTip1: "Requires 150-200 cm annual rainfall or irrigation",
    sugarcaneTip2: "Harvest when sugar content peaks",
    sugarcaneTip3: "Ratoon crops reduce planting costs",
    
    // Image Analysis
    soilAnalysisTitle: "Soil Analysis",
    weatherAnalysisTitle: "Weather Analysis",
    moisture: "Moisture",
    analysisComplete: "Analysis complete!",
    
    // Footer
    footerText: "Empowering farmers with AI-driven insights",
    allRights: "All rights reserved",
  },
  hi: {
    // Header
    appName: "क्रॉपवाइज AI",
    login: "लॉगिन",
    logout: "लॉगआउट",
    language: "भाषा",
    
    // Hero Section
    aiBadge: "AI-संचालित कृषि",
    heroTitle: "स्मार्ट खेती यहाँ से शुरू होती है",
    heroSubtitle: "अपनी मिट्टी, जलवायु और संसाधनों के अनुसार AI-संचालित फसल सिफारिशें प्राप्त करें",
    getStarted: "शुरू करें",
    learnMore: "और जानें",
    cropTypes: "फसल प्रकार",
    accuracy: "सटीकता",
    farmers: "किसान",
    
    // Form
    formTitle: "अपने खेत के बारे में बताएं",
    formSubtitle: "व्यक्तिगत फसल सिफारिशें पाने के लिए अपने खेत का विवरण भरें",
    soilType: "मिट्टी का प्रकार",
    selectSoilType: "मिट्टी का प्रकार चुनें",
    climate: "जलवायु",
    selectClimate: "जलवायु चुनें",
    waterAvailability: "पानी की उपलब्धता",
    selectWaterAvailability: "पानी की उपलब्धता चुनें",
    farmSize: "खेत का आकार (एकड़)",
    enterFarmSize: "खेत का आकार दर्ज करें",
    season: "उगाने का मौसम",
    selectSeason: "मौसम चुनें",
    getRecommendations: "फसल सिफारिशें प्राप्त करें",
    analyzing: "विश्लेषण हो रहा है...",
    
    // Image Upload
    orUploadImage: "या फोटो अपलोड करें",
    uploadImageDesc: "AI सिफारिशें पाने के लिए अपनी मिट्टी, मौसम की स्थिति या फसल की फोटो अपलोड करें",
    uploadPhoto: "फोटो अपलोड करें",
    analyzeImage: "चित्र विश्लेषण करें",
    analyzingImage: "विश्लेषण हो रहा है...",
    
    // Soil types
    clay: "चिकनी मिट्टी",
    sandy: "रेतीली मिट्टी",
    loamy: "दोमट मिट्टी",
    silt: "गाद मिट्टी",
    peat: "पीट मिट्टी",
    chalky: "चूना मिट्टी",
    
    // Climate
    tropical: "उष्णकटिबंधीय",
    subtropical: "उपोष्णकटिबंधीय",
    temperate: "समशीतोष्ण",
    arid: "शुष्क/सूखा",
    semiarid: "अर्ध-शुष्क",
    
    // Water
    abundant: "प्रचुर (सिंचाई)",
    moderate: "मध्यम (मौसमी बारिश)",
    limited: "सीमित (सूखा क्षेत्र)",
    rainfed: "केवल वर्षा आधारित",
    
    // Seasons
    kharif: "खरीफ (मानसून)",
    rabi: "रबी (सर्दी)",
    zaid: "जायद (गर्मी)",
    yearround: "साल भर",
    
    // Results
    recommendedCrops: "आपकी अनुशंसित फसलें",
    basedOnConditions: "आपके खेत की स्थिति के आधार पर, हमारा AI इष्टतम विकास और उपज के लिए इन फसलों की सिफारिश करता है।",
    tryDifferent: "अलग स्थिति आज़माएं",
    downloadReport: "रिपोर्ट डाउनलोड करें",
    
    // Crop Card
    water: "पानी",
    sunlight: "धूप",
    growth: "विकास",
    yield: "उपज",
    growingTips: "उगाने के सुझाव",
    match: "मिलान",
    
    // Water levels
    waterLow: "कम",
    waterMedium: "मध्यम",
    waterHigh: "अधिक",
    
    // Sunlight levels
    fullSun: "पूर्ण धूप",
    partialShade: "आंशिक छाया",
    shadeTolerant: "छाया सहनशील",
    
    // Yield levels
    yieldLow: "कम",
    yieldMedium: "मध्यम",
    yieldHigh: "अधिक",
    
    // Crop names
    rice: "चावल",
    wheat: "गेहूं",
    corn: "मक्का",
    soybean: "सोयाबीन",
    cotton: "कपास",
    millet: "बाजरा",
    potatoes: "आलू",
    tomatoes: "टमाटर",
    sorghum: "ज्वार",
    sugarcane: "गन्ना",
    
    // Crop descriptions
    riceDesc: "एक मुख्य अनाज की फसल जो जलभराव वाली स्थितियों में पनपती है। प्रचुर पानी के साथ उष्णकटिबंधीय और उपोष्णकटिबंधीय जलवायु के लिए आदर्श।",
    wheatDesc: "एक ठंडी मौसम की अनाज फसल जो समशीतोष्ण जलवायु में मध्यम पानी की उपलब्धता के साथ अच्छा प्रदर्शन करती है।",
    cornDesc: "मध्यम से अच्छी पानी की आपूर्ति के साथ गर्म जलवायु के लिए उपयुक्त एक बहुमुखी फसल। विभिन्न मिट्टी प्रकारों के लिए उत्कृष्ट।",
    soybeanDesc: "एक नाइट्रोजन-फिक्सिंग फलीदार फसल जो मिट्टी को समृद्ध करती है। अच्छी जल निकासी वाली दोमट मिट्टी में गर्म परिस्थितियों में पनपती है।",
    cottonDesc: "एक रेशा फसल जो गर्म, अर्ध-शुष्क परिस्थितियों में पनपती है। विभिन्न मिट्टी प्रकारों को सहन करती है लेकिन गहरी, अच्छी जल निकासी वाली मिट्टी पसंद करती है।",
    milletDesc: "सीमित पानी वाले शुष्क क्षेत्रों के लिए एक सूखा-सहिष्णु अनाज। रेतीली और खराब मिट्टी में अच्छी तरह उगता है।",
    potatoesDesc: "एक कंद फसल जो ढीली, अच्छी जल निकासी वाली दोमट मिट्टी के साथ ठंडी समशीतोष्ण जलवायु में उत्कृष्ट प्रदर्शन करती है।",
    tomatoesDesc: "एक गर्म मौसम की सब्जी जिसे लगातार पानी और पोषक तत्वों की आवश्यकता होती है। दोमट, अच्छी जल निकासी वाली मिट्टी में सर्वोत्तम।",
    sorghumDesc: "गर्म, शुष्क जलवायु के लिए एक सूखा-प्रतिरोधी अनाज। अनाज, चारे और जैव ईंधन के लिए बहुमुखी फसल।",
    sugarcaneDesc: "एक उष्णकटिबंधीय घास फसल जिसे प्रचुर पानी और धूप की आवश्यकता होती है। अच्छी जल निकासी के साथ गहरी, उपजाऊ मिट्टी में पनपती है।",
    
    // Crop tips
    riceTip1: "वनस्पति विकास के दौरान 2-5 सेमी खड़ा पानी बनाए रखें",
    riceTip2: "नाइट्रोजन उर्वरक को विभाजित खुराक में लगाएं",
    riceTip3: "आर्द्र परिस्थितियों में ब्लास्ट रोग की निगरानी करें",
    wheatTip1: "मिट्टी का तापमान 10-15°C के बीच होने पर बुवाई करें",
    wheatTip2: "जड़ सड़न रोकने के लिए अच्छी जल निकासी सुनिश्चित करें",
    wheatTip3: "मजबूत जड़ विकास के लिए बुवाई के समय फास्फोरस लगाएं",
    cornTip1: "मिट्टी का तापमान 16°C तक पहुंचने पर बुवाई करें",
    cornTip2: "पौधों को पंक्तियों में 20-30 सेमी की दूरी पर लगाएं",
    cornTip3: "झंडा और रेशम अवस्था में सिंचाई महत्वपूर्ण है",
    soybeanTip1: "नाइट्रोजन स्थिरीकरण के लिए बीजों को राइज़ोबियम से उपचारित करें",
    soybeanTip2: "फूल आने के दौरान जलभराव से बचें",
    soybeanTip3: "मिट्टी के स्वास्थ्य के लिए अनाज के साथ फसल चक्र अपनाएं",
    cottonTip1: "180+ दिनों की पाला-मुक्त उगाने की अवधि आवश्यक है",
    cottonTip2: "बॉलवर्म और सफेद मक्खी की निगरानी करें",
    cottonTip3: "रेशे की गुणवत्ता सुधार के लिए पोटाशियम लगाएं",
    milletTip1: "स्थापित होने के बाद अत्यधिक सूखा सहनशील",
    milletTip2: "न्यूनतम उर्वरक आवश्यकता",
    milletTip3: "आपातकालीन चारा फसल के रूप में काम कर सकता है",
    potatoesTip1: "पौधों के बढ़ने पर मिट्टी चढ़ाएं",
    potatoesTip2: "हरा होने से रोकने के लिए कंदों को ढका रखें",
    potatoesTip3: "मिट्टी जनित रोगों को रोकने के लिए फसल चक्र अपनाएं",
    tomatoesTip1: "बेहतर वायु संचार के लिए पौधों को सहारा दें",
    tomatoesTip2: "मिट्टी की नमी बनाए रखने के लिए मल्च करें",
    tomatoesTip3: "बड़े फलों के लिए सकर्स को छांटें",
    sorghumTip1: "गहरी जड़ प्रणाली सूखे में जीवित रहने में सक्षम बनाती है",
    sorghumTip2: "दूसरी फसल के लिए रेटून कर सकते हैं",
    sorghumTip3: "परिपक्वता के समय पक्षी क्षति नियंत्रित करें",
    sugarcaneTip1: "150-200 सेमी वार्षिक वर्षा या सिंचाई आवश्यक",
    sugarcaneTip2: "चीनी सामग्री अधिकतम होने पर कटाई करें",
    sugarcaneTip3: "रेटून फसलें रोपण लागत कम करती हैं",
    
    // Image Analysis
    soilAnalysisTitle: "मिट्टी विश्लेषण",
    weatherAnalysisTitle: "मौसम विश्लेषण",
    moisture: "नमी",
    analysisComplete: "विश्लेषण पूर्ण!",
    
    // Footer
    footerText: "AI-संचालित अंतर्दृष्टि के साथ किसानों को सशक्त बनाना",
    allRights: "सर्वाधिकार सुरक्षित",
  },
  pa: {
    appName: "ਕ੍ਰੌਪਵਾਈਜ਼ AI",
    login: "ਲੌਗਇਨ",
    logout: "ਲੌਗਆਊਟ",
    language: "ਭਾਸ਼ਾ",
    aiBadge: "AI-ਸੰਚਾਲਿਤ ਖੇਤੀ",
    heroTitle: "ਸਮਾਰਟ ਖੇਤੀ ਇੱਥੇ ਸ਼ੁਰੂ ਹੁੰਦੀ ਹੈ",
    heroSubtitle: "ਆਪਣੀ ਮਿੱਟੀ, ਮੌਸਮ ਅਤੇ ਸਰੋਤਾਂ ਦੇ ਅਨੁਸਾਰ AI-ਸੰਚਾਲਿਤ ਫਸਲ ਸਿਫਾਰਸ਼ਾਂ ਪ੍ਰਾਪਤ ਕਰੋ",
    getStarted: "ਸ਼ੁਰੂ ਕਰੋ",
    learnMore: "ਹੋਰ ਜਾਣੋ",
    cropTypes: "ਫਸਲ ਕਿਸਮਾਂ",
    accuracy: "ਸਹੀਤਾ",
    farmers: "ਕਿਸਾਨ",
    formTitle: "ਆਪਣੇ ਖੇਤ ਬਾਰੇ ਦੱਸੋ",
    formSubtitle: "ਨਿੱਜੀ ਫਸਲ ਸਿਫਾਰਸ਼ਾਂ ਲਈ ਆਪਣੇ ਖੇਤ ਦਾ ਵੇਰਵਾ ਭਰੋ",
    soilType: "ਮਿੱਟੀ ਦੀ ਕਿਸਮ",
    selectSoilType: "ਮਿੱਟੀ ਦੀ ਕਿਸਮ ਚੁਣੋ",
    climate: "ਮੌਸਮ",
    selectClimate: "ਮੌਸਮ ਚੁਣੋ",
    waterAvailability: "ਪਾਣੀ ਦੀ ਉਪਲਬਧਤਾ",
    selectWaterAvailability: "ਪਾਣੀ ਦੀ ਉਪਲਬਧਤਾ ਚੁਣੋ",
    farmSize: "ਖੇਤ ਦਾ ਆਕਾਰ (ਏਕੜ)",
    enterFarmSize: "ਖੇਤ ਦਾ ਆਕਾਰ ਦਰਜ ਕਰੋ",
    season: "ਉਗਾਉਣ ਦਾ ਮੌਸਮ",
    selectSeason: "ਮੌਸਮ ਚੁਣੋ",
    getRecommendations: "ਫਸਲ ਸਿਫਾਰਸ਼ਾਂ ਪ੍ਰਾਪਤ ਕਰੋ",
    analyzing: "ਵਿਸ਼ਲੇਸ਼ਣ ਹੋ ਰਿਹਾ ਹੈ...",
    orUploadImage: "ਜਾਂ ਫੋਟੋ ਅੱਪਲੋਡ ਕਰੋ",
    uploadImageDesc: "AI ਸਿਫਾਰਸ਼ਾਂ ਲਈ ਆਪਣੀ ਮਿੱਟੀ, ਮੌਸਮ ਜਾਂ ਫਸਲ ਦੀ ਫੋਟੋ ਅੱਪਲੋਡ ਕਰੋ",
    uploadPhoto: "ਫੋਟੋ ਅੱਪਲੋਡ ਕਰੋ",
    analyzeImage: "ਚਿੱਤਰ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ",
    analyzingImage: "ਵਿਸ਼ਲੇਸ਼ਣ ਹੋ ਰਿਹਾ ਹੈ...",
    clay: "ਚਿਕਨੀ ਮਿੱਟੀ",
    sandy: "ਰੇਤਲੀ ਮਿੱਟੀ",
    loamy: "ਦੋਮਟ ਮਿੱਟੀ",
    silt: "ਸਿਲਟ ਮਿੱਟੀ",
    peat: "ਪੀਟ ਮਿੱਟੀ",
    chalky: "ਚੂਨਾ ਮਿੱਟੀ",
    tropical: "ਗਰਮ",
    subtropical: "ਉਪ-ਗਰਮ",
    temperate: "ਸਮਸ਼ੀਤੋਸ਼ਣ",
    arid: "ਸੁੱਕਾ",
    semiarid: "ਅਰਧ-ਸੁੱਕਾ",
    abundant: "ਭਰਪੂਰ (ਸਿੰਚਾਈ)",
    moderate: "ਮੱਧਮ (ਮੌਸਮੀ ਬਾਰਸ਼)",
    limited: "ਸੀਮਿਤ (ਸੁੱਕਾ ਖੇਤਰ)",
    rainfed: "ਸਿਰਫ਼ ਬਾਰਸ਼ ਆਧਾਰਿਤ",
    kharif: "ਖਰੀਫ਼ (ਮੌਨਸੂਨ)",
    rabi: "ਰਬੀ (ਸਰਦੀ)",
    zaid: "ਜ਼ਾਇਦ (ਗਰਮੀ)",
    yearround: "ਸਾਲ ਭਰ",
    recommendedCrops: "ਤੁਹਾਡੀਆਂ ਸਿਫਾਰਸ਼ੀ ਫਸਲਾਂ",
    basedOnConditions: "ਤੁਹਾਡੇ ਖੇਤ ਦੀ ਸਥਿਤੀ ਦੇ ਆਧਾਰ ਤੇ, ਸਾਡਾ AI ਵਧੀਆ ਵਾਧੇ ਅਤੇ ਝਾੜ ਲਈ ਇਨ੍ਹਾਂ ਫਸਲਾਂ ਦੀ ਸਿਫਾਰਸ਼ ਕਰਦਾ ਹੈ।",
    tryDifferent: "ਵੱਖਰੀ ਸਥਿਤੀ ਅਜ਼ਮਾਓ",
    downloadReport: "ਰਿਪੋਰਟ ਡਾਊਨਲੋਡ ਕਰੋ",
    water: "ਪਾਣੀ",
    sunlight: "ਧੁੱਪ",
    growth: "ਵਿਕਾਸ",
    yield: "ਝਾੜ",
    growingTips: "ਉਗਾਉਣ ਦੇ ਸੁਝਾਅ",
    match: "ਮਿਲਾਨ",
    rice: "ਚੌਲ",
    wheat: "ਕਣਕ",
    corn: "ਮੱਕੀ",
    soybean: "ਸੋਇਆਬੀਨ",
    cotton: "ਕਪਾਹ",
    millet: "ਬਾਜਰਾ",
    potatoes: "ਆਲੂ",
    tomatoes: "ਟਮਾਟਰ",
    sorghum: "ਜਵਾਰ",
    sugarcane: "ਗੰਨਾ",
    // Water levels
    waterLow: "ਘੱਟ",
    waterMedium: "ਮੱਧਮ",
    waterHigh: "ਜ਼ਿਆਦਾ",
    // Sunlight levels
    fullSun: "ਪੂਰੀ ਧੁੱਪ",
    partialShade: "ਅੰਸ਼ਕ ਛਾਂ",
    shadeTolerant: "ਛਾਂ ਸਹਿਣਸ਼ੀਲ",
    // Yield levels
    yieldLow: "ਘੱਟ",
    yieldMedium: "ਮੱਧਮ",
    yieldHigh: "ਜ਼ਿਆਦਾ",
    // Crop descriptions
    riceDesc: "ਇੱਕ ਮੁੱਖ ਅਨਾਜ ਦੀ ਫਸਲ ਜੋ ਪਾਣੀ ਭਰੀ ਹਾਲਤ ਵਿੱਚ ਵਧਦੀ ਹੈ। ਭਰਪੂਰ ਪਾਣੀ ਵਾਲੇ ਗਰਮ ਖੇਤਰਾਂ ਲਈ ਆਦਰਸ਼।",
    wheatDesc: "ਠੰਡੇ ਮੌਸਮ ਦੀ ਅਨਾਜ ਫਸਲ ਜੋ ਮੱਧਮ ਪਾਣੀ ਦੀ ਉਪਲਬਧਤਾ ਨਾਲ ਚੰਗਾ ਪ੍ਰਦਰਸ਼ਨ ਕਰਦੀ ਹੈ।",
    cornDesc: "ਮੱਧਮ ਤੋਂ ਚੰਗੀ ਪਾਣੀ ਸਪਲਾਈ ਨਾਲ ਗਰਮ ਮੌਸਮ ਲਈ ਢੁਕਵੀਂ ਬਹੁਮੁਖੀ ਫਸਲ।",
    soybeanDesc: "ਨਾਈਟ੍ਰੋਜਨ-ਫਿਕਸਿੰਗ ਦਾਲ ਜੋ ਮਿੱਟੀ ਨੂੰ ਸਮਰਿੱਧ ਕਰਦੀ ਹੈ। ਚੰਗੀ ਨਿਕਾਸੀ ਵਾਲੀ ਦੋਮਟ ਮਿੱਟੀ ਵਿੱਚ ਵਧਦੀ ਹੈ।",
    cottonDesc: "ਰੇਸ਼ੇ ਦੀ ਫਸਲ ਜੋ ਗਰਮ, ਅਰਧ-ਸੁੱਕੇ ਹਾਲਾਤਾਂ ਵਿੱਚ ਵਧਦੀ ਹੈ।",
    milletDesc: "ਸੀਮਤ ਪਾਣੀ ਵਾਲੇ ਸੁੱਕੇ ਖੇਤਰਾਂ ਲਈ ਸੋਕਾ-ਸਹਿਣਸ਼ੀਲ ਅਨਾਜ।",
    potatoesDesc: "ਇੱਕ ਕੰਦ ਫਸਲ ਜੋ ਢਿੱਲੀ, ਚੰਗੀ ਨਿਕਾਸੀ ਵਾਲੀ ਦੋਮਟ ਮਿੱਟੀ ਨਾਲ ਠੰਡੇ ਮੌਸਮ ਵਿੱਚ ਚੰਗਾ ਕਰਦੀ ਹੈ।",
    tomatoesDesc: "ਗਰਮ ਮੌਸਮ ਦੀ ਸਬਜ਼ੀ ਜਿਸ ਨੂੰ ਲਗਾਤਾਰ ਪਾਣੀ ਅਤੇ ਪੋਸ਼ਕ ਤੱਤਾਂ ਦੀ ਲੋੜ ਹੈ।",
    sorghumDesc: "ਗਰਮ, ਸੁੱਕੇ ਮੌਸਮ ਲਈ ਸੋਕਾ-ਰੋਧੀ ਅਨਾਜ। ਅਨਾਜ, ਚਾਰੇ ਅਤੇ ਜੈਵ ਈਂਧਨ ਲਈ ਬਹੁਮੁਖੀ ਫਸਲ।",
    sugarcaneDesc: "ਗਰਮ ਖੇਤਰ ਦੀ ਘਾਹ ਫਸਲ ਜਿਸ ਨੂੰ ਭਰਪੂਰ ਪਾਣੀ ਅਤੇ ਧੁੱਪ ਦੀ ਲੋੜ ਹੈ।",
    // Crop tips
    riceTip1: "ਵਾਧੇ ਦੌਰਾਨ 2-5 ਸੈਂਟੀਮੀਟਰ ਖੜ੍ਹਾ ਪਾਣੀ ਰੱਖੋ",
    riceTip2: "ਨਾਈਟ੍ਰੋਜਨ ਖਾਦ ਵੰਡ ਕੇ ਦਿਓ",
    riceTip3: "ਨਮੀ ਵਾਲੇ ਹਾਲਾਤਾਂ ਵਿੱਚ ਬਲਾਸਟ ਬਿਮਾਰੀ ਦੀ ਨਿਗਰਾਨੀ ਕਰੋ",
    wheatTip1: "ਮਿੱਟੀ ਦਾ ਤਾਪਮਾਨ 10-15°C ਹੋਣ ਤੇ ਬੀਜੋ",
    wheatTip2: "ਜੜ੍ਹ ਸੜਨ ਰੋਕਣ ਲਈ ਚੰਗੀ ਨਿਕਾਸੀ ਯਕੀਨੀ ਬਣਾਓ",
    wheatTip3: "ਮਜ਼ਬੂਤ ਜੜ੍ਹ ਵਿਕਾਸ ਲਈ ਬਿਜਾਈ ਵੇਲੇ ਫਾਸਫੋਰਸ ਲਗਾਓ",
    cornTip1: "ਮਿੱਟੀ ਦਾ ਤਾਪਮਾਨ 16°C ਹੋਣ ਤੇ ਬੀਜੋ",
    cornTip2: "ਬੂਟਿਆਂ ਨੂੰ 20-30 ਸੈਂਟੀਮੀਟਰ ਦੂਰੀ ਤੇ ਲਗਾਓ",
    cornTip3: "ਝੰਡੇ ਅਤੇ ਰੇਸ਼ਮ ਅਵਸਥਾ ਵਿੱਚ ਸਿੰਚਾਈ ਮਹੱਤਵਪੂਰਨ ਹੈ",
    soybeanTip1: "ਨਾਈਟ੍ਰੋਜਨ ਸਥਿਰੀਕਰਨ ਲਈ ਬੀਜਾਂ ਨੂੰ ਰਾਈਜ਼ੋਬੀਅਮ ਨਾਲ ਉਪਚਾਰ ਕਰੋ",
    soybeanTip2: "ਫੁੱਲ ਆਉਣ ਵੇਲੇ ਪਾਣੀ ਖੜ੍ਹਾ ਨਾ ਹੋਣ ਦਿਓ",
    soybeanTip3: "ਮਿੱਟੀ ਦੀ ਸਿਹਤ ਲਈ ਅਨਾਜਾਂ ਨਾਲ ਫਸਲ ਚੱਕਰ ਅਪਣਾਓ",
    cottonTip1: "180+ ਦਿਨਾਂ ਦੀ ਪਾਲਾ-ਮੁਕਤ ਉਗਾਉਣ ਦੀ ਮਿਆਦ ਲੋੜੀਂਦੀ ਹੈ",
    cottonTip2: "ਬੋਲਵਰਮ ਅਤੇ ਚਿੱਟੀ ਮੱਖੀ ਦੀ ਨਿਗਰਾਨੀ ਕਰੋ",
    cottonTip3: "ਰੇਸ਼ੇ ਦੀ ਗੁਣਵੱਤਾ ਸੁਧਾਰ ਲਈ ਪੋਟਾਸ਼ੀਅਮ ਲਗਾਓ",
    milletTip1: "ਸਥਾਪਿਤ ਹੋਣ ਤੋਂ ਬਾਅਦ ਬਹੁਤ ਸੋਕਾ ਸਹਿਣਸ਼ੀਲ",
    milletTip2: "ਘੱਟੋ-ਘੱਟ ਖਾਦ ਦੀ ਲੋੜ",
    milletTip3: "ਐਮਰਜੈਂਸੀ ਚਾਰਾ ਫਸਲ ਵਜੋਂ ਕੰਮ ਕਰ ਸਕਦੀ ਹੈ",
    potatoesTip1: "ਬੂਟਿਆਂ ਦੇ ਵਧਣ ਨਾਲ ਮਿੱਟੀ ਚੜ੍ਹਾਓ",
    potatoesTip2: "ਹਰੇ ਹੋਣ ਤੋਂ ਰੋਕਣ ਲਈ ਕੰਦਾਂ ਨੂੰ ਢੱਕ ਕੇ ਰੱਖੋ",
    potatoesTip3: "ਮਿੱਟੀ ਤੋਂ ਪੈਦਾ ਬਿਮਾਰੀਆਂ ਰੋਕਣ ਲਈ ਫਸਲ ਚੱਕਰ ਅਪਣਾਓ",
    tomatoesTip1: "ਬਿਹਤਰ ਹਵਾ ਸੰਚਾਰ ਲਈ ਬੂਟਿਆਂ ਨੂੰ ਸਹਾਰਾ ਦਿਓ",
    tomatoesTip2: "ਮਿੱਟੀ ਦੀ ਨਮੀ ਬਣਾਈ ਰੱਖਣ ਲਈ ਮਲਚ ਕਰੋ",
    tomatoesTip3: "ਵੱਡੇ ਫਲਾਂ ਲਈ ਸਕਰਜ਼ ਛਾਂਟੋ",
    sorghumTip1: "ਡੂੰਘੀ ਜੜ੍ਹ ਪ੍ਰਣਾਲੀ ਸੋਕੇ ਵਿੱਚ ਬਚਾਅ ਦਿੰਦੀ ਹੈ",
    sorghumTip2: "ਦੂਜੀ ਵਾਢੀ ਲਈ ਰਿਟੂਨ ਕਰ ਸਕਦੇ ਹੋ",
    sorghumTip3: "ਪੱਕਣ ਵੇਲੇ ਪੰਛੀਆਂ ਦਾ ਨੁਕਸਾਨ ਕੰਟਰੋਲ ਕਰੋ",
    sugarcaneTip1: "150-200 ਸੈਂਟੀਮੀਟਰ ਸਾਲਾਨਾ ਬਾਰਸ਼ ਜਾਂ ਸਿੰਚਾਈ ਲੋੜੀਂਦੀ ਹੈ",
    sugarcaneTip2: "ਖੰਡ ਸਮੱਗਰੀ ਵੱਧ ਹੋਣ ਤੇ ਵਾਢੀ ਕਰੋ",
    sugarcaneTip3: "ਰਿਟੂਨ ਫਸਲਾਂ ਬਿਜਾਈ ਖਰਚ ਘਟਾਉਂਦੀਆਂ ਹਨ",
    soilAnalysisTitle: "ਮਿੱਟੀ ਵਿਸ਼ਲੇਸ਼ਣ",
    weatherAnalysisTitle: "ਮੌਸਮ ਵਿਸ਼ਲੇਸ਼ਣ",
    moisture: "ਨਮੀ",
    analysisComplete: "ਵਿਸ਼ਲੇਸ਼ਣ ਪੂਰਾ!",
    footerText: "AI-ਸੰਚਾਲਿਤ ਜਾਣਕਾਰੀ ਨਾਲ ਕਿਸਾਨਾਂ ਨੂੰ ਸਸ਼ਕਤ ਬਣਾਉਣਾ",
    allRights: "ਸਾਰੇ ਹੱਕ ਰਾਖਵੇਂ ਹਨ",
  },
  mr: {
    appName: "क्रॉपवाइज AI",
    login: "लॉगिन",
    logout: "लॉगआउट",
    language: "भाषा",
    aiBadge: "AI-चालित शेती",
    heroTitle: "स्मार्ट शेती इथे सुरू होते",
    heroSubtitle: "तुमच्या माती, हवामान आणि संसाधनांनुसार AI-चालित पीक शिफारसी मिळवा",
    getStarted: "सुरू करा",
    learnMore: "अधिक जाणून घ्या",
    cropTypes: "पीक प्रकार",
    accuracy: "अचूकता",
    farmers: "शेतकरी",
    formTitle: "तुमच्या शेताबद्दल सांगा",
    formSubtitle: "वैयक्तिक पीक शिफारसींसाठी तुमच्या शेताचा तपशील भरा",
    soilType: "मातीचा प्रकार",
    selectSoilType: "मातीचा प्रकार निवडा",
    climate: "हवामान",
    selectClimate: "हवामान निवडा",
    waterAvailability: "पाण्याची उपलब्धता",
    selectWaterAvailability: "पाण्याची उपलब्धता निवडा",
    farmSize: "शेताचा आकार (एकर)",
    enterFarmSize: "शेताचा आकार प्रविष्ट करा",
    season: "वाढीचा हंगाम",
    selectSeason: "हंगाम निवडा",
    getRecommendations: "पीक शिफारसी मिळवा",
    analyzing: "विश्लेषण होत आहे...",
    orUploadImage: "किंवा फोटो अपलोड करा",
    uploadImageDesc: "AI शिफारसींसाठी तुमची माती, हवामान किंवा पीक फोटो अपलोड करा",
    uploadPhoto: "फोटो अपलोड करा",
    analyzeImage: "चित्र विश्लेषण करा",
    analyzingImage: "विश्लेषण होत आहे...",
    clay: "चिकणमाती",
    sandy: "वाळूमाती",
    loamy: "गाळमाती",
    silt: "सिल्ट माती",
    peat: "पीट माती",
    chalky: "चुनखडी माती",
    tropical: "उष्णकटिबंधीय",
    subtropical: "उपोष्णकटिबंधीय",
    temperate: "समशीतोष्ण",
    arid: "कोरडे",
    semiarid: "अर्ध-कोरडे",
    abundant: "भरपूर (सिंचन)",
    moderate: "मध्यम (हंगामी पाऊस)",
    limited: "मर्यादित (कोरडा प्रदेश)",
    rainfed: "फक्त पावसावर अवलंबून",
    kharif: "खरीप (मान्सून)",
    rabi: "रब्बी (हिवाळा)",
    zaid: "उन्हाळी",
    yearround: "वर्षभर",
    recommendedCrops: "तुमची शिफारस केलेली पिके",
    basedOnConditions: "तुमच्या शेताच्या परिस्थितीवर आधारित, आमचे AI सर्वोत्तम वाढ आणि उत्पादनासाठी या पिकांची शिफारस करते.",
    tryDifferent: "वेगळी परिस्थिती वापरून पहा",
    downloadReport: "अहवाल डाउनलोड करा",
    water: "पाणी",
    sunlight: "सूर्यप्रकाश",
    growth: "वाढ",
    yield: "उत्पादन",
    growingTips: "वाढीचे सुझाव",
    match: "मिळान",
    rice: "भात",
    wheat: "गहू",
    corn: "मका",
    soybean: "सोयाबीन",
    cotton: "कापूस",
    millet: "बाजरी",
    potatoes: "बटाटे",
    tomatoes: "टोमॅटो",
    sorghum: "ज्वारी",
    sugarcane: "ऊस",
    // Water levels
    waterLow: "कमी",
    waterMedium: "मध्यम",
    waterHigh: "जास्त",
    // Sunlight levels
    fullSun: "पूर्ण सूर्यप्रकाश",
    partialShade: "आंशिक सावली",
    shadeTolerant: "सावली सहनशील",
    // Yield levels
    yieldLow: "कमी",
    yieldMedium: "मध्यम",
    yieldHigh: "जास्त",
    // Crop descriptions
    riceDesc: "एक मुख्य धान्य पीक जे पाणी साठलेल्या परिस्थितीत वाढते. भरपूर पाण्यासह उष्णकटिबंधीय हवामानासाठी आदर्श.",
    wheatDesc: "थंड हंगामातील धान्य पीक जे मध्यम पाण्याच्या उपलब्धतेसह समशीतोष्ण हवामानात चांगले वाढते.",
    cornDesc: "मध्यम ते चांगल्या पाण्याच्या पुरवठ्यासह उबदार हवामानासाठी योग्य बहुउद्देशीय पीक.",
    soybeanDesc: "नायट्रोजन-फिक्सिंग शेंगदाणा पीक जे मातीला समृद्ध करते. चांगल्या निचऱ्याच्या गाळमातीत वाढते.",
    cottonDesc: "तंतू पीक जे उबदार, अर्ध-कोरड्या परिस्थितीत वाढते. विविध माती प्रकार सहन करते.",
    milletDesc: "मर्यादित पाण्यासह कोरड्या प्रदेशांसाठी दुष्काळ-सहनशील धान्य. वाळू आणि खराब मातीत चांगले वाढते.",
    potatoesDesc: "एक कंद पीक जे सैल, चांगल्या निचऱ्याच्या गाळमातीसह थंड हवामानात उत्कृष्ट कामगिरी करते.",
    tomatoesDesc: "उबदार हंगामातील भाजी ज्याला सातत्यपूर्ण पाणी आणि पोषक तत्वांची आवश्यकता असते.",
    sorghumDesc: "गरम, कोरड्या हवामानासाठी दुष्काळ-प्रतिरोधक धान्य. धान्य, चारा आणि जैव इंधनासाठी बहुउद्देशीय पीक.",
    sugarcaneDesc: "उष्णकटिबंधीय गवत पीक ज्याला भरपूर पाणी आणि सूर्यप्रकाश आवश्यक आहे.",
    // Crop tips
    riceTip1: "वाढीच्या काळात 2-5 सेमी उभे पाणी राखा",
    riceTip2: "नायट्रोजन खत विभाजित डोसमध्ये द्या",
    riceTip3: "दमट परिस्थितीत ब्लास्ट रोगावर लक्ष ठेवा",
    wheatTip1: "मातीचे तापमान 10-15°C दरम्यान असताना पेरणी करा",
    wheatTip2: "मुळे कुजणे टाळण्यासाठी चांगला निचरा सुनिश्चित करा",
    wheatTip3: "मजबूत मुळांच्या विकासासाठी पेरणीच्या वेळी फॉस्फरस द्या",
    cornTip1: "मातीचे तापमान 16°C पोहोचल्यावर पेरणी करा",
    cornTip2: "रोपे 20-30 सेमी अंतरावर लावा",
    cornTip3: "तुऱ्या आणि रेशीम अवस्थेत सिंचन महत्त्वाचे आहे",
    soybeanTip1: "नायट्रोजन स्थिरीकरणासाठी बियाण्यांवर रायझोबियम उपचार करा",
    soybeanTip2: "फुलांच्या काळात पाणी साठणे टाळा",
    soybeanTip3: "मातीच्या आरोग्यासाठी धान्यांसह पीक फेरपालट करा",
    cottonTip1: "180+ दिवसांचा दंव-मुक्त वाढीचा कालावधी आवश्यक आहे",
    cottonTip2: "बोंडअळी आणि पांढरी माशी यांवर लक्ष ठेवा",
    cottonTip3: "तंतू गुणवत्ता सुधारण्यासाठी पोटॅशियम द्या",
    milletTip1: "स्थापित झाल्यावर अत्यंत दुष्काळ सहनशील",
    milletTip2: "किमान खताची आवश्यकता",
    milletTip3: "आणीबाणी चारा पीक म्हणून काम करू शकते",
    potatoesTip1: "रोपे वाढत असताना माती चढवा",
    potatoesTip2: "हिरवे होणे टाळण्यासाठी कंद झाकून ठेवा",
    potatoesTip3: "माती-जन्य रोग टाळण्यासाठी पीक फेरपालट करा",
    tomatoesTip1: "चांगल्या हवा संचारासाठी रोपांना आधार द्या",
    tomatoesTip2: "मातीतील ओलावा राखण्यासाठी आच्छादन करा",
    tomatoesTip3: "मोठ्या फळांसाठी सकर्स छाटा",
    sorghumTip1: "खोल मूळ प्रणाली दुष्काळात टिकून राहण्यास सक्षम करते",
    sorghumTip2: "दुसऱ्या कापणीसाठी रेटून करता येते",
    sorghumTip3: "परिपक्वतेच्या वेळी पक्ष्यांचे नुकसान नियंत्रित करा",
    sugarcaneTip1: "150-200 सेमी वार्षिक पाऊस किंवा सिंचन आवश्यक",
    sugarcaneTip2: "साखरेचे प्रमाण जास्तीत जास्त असताना कापणी करा",
    sugarcaneTip3: "रेटून पिके लागवड खर्च कमी करतात",
    soilAnalysisTitle: "माती विश्लेषण",
    weatherAnalysisTitle: "हवामान विश्लेषण",
    moisture: "ओलावा",
    analysisComplete: "विश्लेषण पूर्ण!",
    footerText: "AI-चालित अंतर्दृष्टीसह शेतकऱ्यांना सक्षम करणे",
    allRights: "सर्व हक्क राखीव",
  },
  ta: {
    appName: "கிராப்வைஸ் AI",
    login: "உள்நுழை",
    logout: "வெளியேறு",
    language: "மொழி",
    aiBadge: "AI-இயக்கப்படும் விவசாயம்",
    heroTitle: "ஸ்மார்ட் விவசாயம் இங்கே தொடங்குகிறது",
    heroSubtitle: "உங்கள் மண், காலநிலை மற்றும் வளங்களுக்கு ஏற்ப AI-இயக்கப்படும் பயிர் பரிந்துரைகளைப் பெறுங்கள்",
    getStarted: "தொடங்கு",
    learnMore: "மேலும் அறிக",
    cropTypes: "பயிர் வகைகள்",
    accuracy: "துல்லியம்",
    farmers: "விவசாயிகள்",
    formTitle: "உங்கள் பண்ணையைப் பற்றி சொல்லுங்கள்",
    formSubtitle: "தனிப்பயன் பயிர் பரிந்துரைகளுக்கு உங்கள் பண்ணை விவரங்களை நிரப்பவும்",
    soilType: "மண் வகை",
    selectSoilType: "மண் வகையைத் தேர்ந்தெடுக்கவும்",
    climate: "காலநிலை",
    selectClimate: "காலநிலையைத் தேர்ந்தெடுக்கவும்",
    waterAvailability: "நீர் கிடைக்கும் தன்மை",
    selectWaterAvailability: "நீர் கிடைக்கும் தன்மையைத் தேர்ந்தெடுக்கவும்",
    farmSize: "பண்ணை அளவு (ஏக்கர்)",
    enterFarmSize: "பண்ணை அளவை உள்ளிடவும்",
    season: "வளர்ப்பு பருவம்",
    selectSeason: "பருவத்தைத் தேர்ந்தெடுக்கவும்",
    getRecommendations: "பயிர் பரிந்துரைகளைப் பெறு",
    analyzing: "பகுப்பாய்வு செய்யப்படுகிறது...",
    orUploadImage: "அல்லது புகைப்படம் பதிவேற்றவும்",
    uploadImageDesc: "AI பரிந்துரைகளுக்கு உங்கள் மண், காலநிலை அல்லது பயிர் புகைப்படத்தை பதிவேற்றவும்",
    uploadPhoto: "புகைப்படம் பதிவேற்றவும்",
    analyzeImage: "படத்தை பகுப்பாய்வு செய்",
    analyzingImage: "பகுப்பாய்வு செய்யப்படுகிறது...",
    clay: "களிமண்",
    sandy: "மணல் மண்",
    loamy: "செழிப்பான மண்",
    silt: "வண்டல் மண்",
    peat: "பீட் மண்",
    chalky: "சுண்ணாம்பு மண்",
    tropical: "வெப்ப மண்டல",
    subtropical: "துணை வெப்ப மண்டல",
    temperate: "மிதமான",
    arid: "வறண்ட",
    semiarid: "அரை வறண்ட",
    abundant: "ஏராளமான (பாசன)",
    moderate: "மிதமான (பருவ மழை)",
    limited: "குறைவான (வறண்ட பகுதி)",
    rainfed: "மழை நீர் மட்டும்",
    kharif: "கரீஃப் (பருவமழை)",
    rabi: "ரபி (குளிர்காலம்)",
    zaid: "ஜாய்த் (கோடைக்காலம்)",
    yearround: "ஆண்டு முழுவதும்",
    recommendedCrops: "உங்கள் பரிந்துரைக்கப்பட்ட பயிர்கள்",
    basedOnConditions: "உங்கள் பண்ணை நிலைமைகளின் அடிப்படையில், சிறந்த வளர்ச்சி மற்றும் விளைச்சலுக்கு எங்கள் AI இந்த பயிர்களை பரிந்துரைக்கிறது.",
    tryDifferent: "வேறு நிலைமைகளை முயற்சிக்கவும்",
    downloadReport: "அறிக்கையைப் பதிவிறக்கு",
    water: "நீர்",
    sunlight: "சூரிய ஒளி",
    growth: "வளர்ச்சி",
    yield: "விளைச்சல்",
    growingTips: "வளர்ப்பு குறிப்புகள்",
    match: "பொருத்தம்",
    rice: "அரிசி",
    wheat: "கோதுமை",
    corn: "சோளம்",
    soybean: "சோயாபீன்",
    cotton: "பருத்தி",
    millet: "கம்பு",
    potatoes: "உருளைக்கிழங்கு",
    tomatoes: "தக்காளி",
    sorghum: "சோளம்",
    sugarcane: "கரும்பு",
    // Water levels
    waterLow: "குறைவு",
    waterMedium: "நடுத்தரம்",
    waterHigh: "அதிகம்",
    // Sunlight levels
    fullSun: "முழு சூரிய ஒளி",
    partialShade: "பகுதி நிழல்",
    shadeTolerant: "நிழல் தாங்கும்",
    // Yield levels
    yieldLow: "குறைவு",
    yieldMedium: "நடுத்தரம்",
    yieldHigh: "அதிகம்",
    // Crop descriptions
    riceDesc: "நீர் தேங்கிய நிலைகளில் செழிக்கும் முக்கிய தானியப் பயிர். ஏராளமான நீருடன் வெப்பமண்டல காலநிலைக்கு ஏற்றது.",
    wheatDesc: "மிதமான நீர் கிடைக்கும் தன்மையுடன் சமவெளி காலநிலையில் நன்கு வளரும் குளிர் காலத் தானியப் பயிர்.",
    cornDesc: "மிதமான முதல் நல்ல நீர் வழங்கலுடன் சூடான காலநிலைக்கு ஏற்ற பல்துறை பயிர்.",
    soybeanDesc: "மண்ணை வளப்படுத்தும் நைட்ரஜன்-நிலைப்படுத்தும் பயறு வகை. நல்ல வடிகால் செழிப்பான மண்ணில் வளரும்.",
    cottonDesc: "சூடான, அரை வறண்ட நிலைகளில் செழிக்கும் நார் பயிர். பல்வேறு மண் வகைகளை தாங்கும்.",
    milletDesc: "குறைந்த நீருடன் வறண்ட பகுதிகளுக்கு ஏற்ற வறட்சி-தாங்கும் தானியம்.",
    potatoesDesc: "தளர்வான, நல்ல வடிகால் செழிப்பான மண்ணுடன் குளிர்ந்த காலநிலையில் சிறப்பாக வளரும் கிழங்கு பயிர்.",
    tomatoesDesc: "நிலையான நீர் மற்றும் ஊட்டச்சத்துக்கள் தேவைப்படும் சூடான காலக் காய்கறி.",
    sorghumDesc: "வெப்பமான, வறண்ட காலநிலைக்கு ஏற்ற வறட்சி-எதிர்ப்பு தானியம். தானியம், தீவனம் மற்றும் உயிரி எரிபொருளுக்கான பல்துறை பயிர்.",
    sugarcaneDesc: "ஏராளமான நீர் மற்றும் சூரிய ஒளி தேவைப்படும் வெப்பமண்டல புல் பயிர்.",
    // Crop tips
    riceTip1: "வளர்ச்சி காலத்தில் 2-5 செமீ நிற்கும் நீரை பராமரிக்கவும்",
    riceTip2: "நைட்ரஜன் உரத்தை பிரிந்த அளவுகளில் கொடுக்கவும்",
    riceTip3: "ஈரப்பதமான நிலைகளில் பிளாஸ்ட் நோயை கவனிக்கவும்",
    wheatTip1: "மண் வெப்பநிலை 10-15°C இருக்கும்போது விதைக்கவும்",
    wheatTip2: "வேர் அழுகலை தடுக்க நல்ல வடிகால் உறுதி செய்யவும்",
    wheatTip3: "வலுவான வேர் வளர்ச்சிக்கு விதைப்பின்போது பாஸ்பரஸ் கொடுக்கவும்",
    cornTip1: "மண் வெப்பநிலை 16°C ஐ எட்டும்போது விதைக்கவும்",
    cornTip2: "செடிகளை 20-30 செமீ இடைவெளியில் நடவும்",
    cornTip3: "தாஸ்ஸலிங் மற்றும் சில்கிங் நிலைகளில் நீர்ப்பாசனம் முக்கியம்",
    soybeanTip1: "நைட்ரஜன் நிலைப்படுத்தலுக்கு விதைகளை ரைசோபியத்துடன் சிகிச்சை செய்யவும்",
    soybeanTip2: "பூக்கும் போது நீர் தேங்குவதை தவிர்க்கவும்",
    soybeanTip3: "மண் ஆரோக்கியத்திற்கு தானியங்களுடன் பயிர் சுழற்சி செய்யவும்",
    cottonTip1: "180+ நாட்கள் உறைபனி இல்லாத வளர்ச்சி காலம் தேவை",
    cottonTip2: "பூச்சி புழு மற்றும் வெள்ளை ஈயை கவனிக்கவும்",
    cottonTip3: "நார் தரத்தை மேம்படுத்த பொட்டாசியம் கொடுக்கவும்",
    milletTip1: "நிலைநிறுத்தப்பட்ட பின் மிகவும் வறட்சி தாங்கும்",
    milletTip2: "குறைந்தபட்ச உர தேவை",
    milletTip3: "அவசர தீவன பயிராக செயல்பட முடியும்",
    potatoesTip1: "செடிகள் வளரும்போது மண் அணைக்கவும்",
    potatoesTip2: "பச்சையாவதை தடுக்க கிழங்குகளை மூடி வைக்கவும்",
    potatoesTip3: "மண் மூலம் பரவும் நோய்களை தடுக்க பயிர் சுழற்சி செய்யவும்",
    tomatoesTip1: "நல்ல காற்று சுழற்சிக்கு செடிகளுக்கு ஊன்றுகோல் கொடுக்கவும்",
    tomatoesTip2: "மண் ஈரப்பதத்தை பராமரிக்க மல்ச் செய்யவும்",
    tomatoesTip3: "பெரிய பழங்களுக்கு சக்கர்களை கத்தரிக்கவும்",
    sorghumTip1: "ஆழமான வேர் அமைப்பு வறட்சியில் உயிர்வாழ உதவுகிறது",
    sorghumTip2: "இரண்டாவது அறுவடைக்கு ரேட்டூன் செய்யலாம்",
    sorghumTip3: "முதிர்ச்சியின் போது பறவை சேதத்தை கட்டுப்படுத்தவும்",
    sugarcaneTip1: "150-200 செமீ வருடாந்திர மழை அல்லது நீர்ப்பாசனம் தேவை",
    sugarcaneTip2: "சர்க்கரை உள்ளடக்கம் அதிகமாக இருக்கும்போது அறுவடை செய்யவும்",
    sugarcaneTip3: "ரேட்டூன் பயிர்கள் நடவு செலவை குறைக்கின்றன",
    soilAnalysisTitle: "மண் பகுப்பாய்வு",
    weatherAnalysisTitle: "வானிலை பகுப்பாய்வு",
    moisture: "ஈரப்பதம்",
    analysisComplete: "பகுப்பாய்வு முடிந்தது!",
    footerText: "AI-இயக்கப்படும் நுண்ணறிவுகளுடன் விவசாயிகளை மேம்படுத்துதல்",
    allRights: "அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை",
  },
  te: {
    appName: "క్రాప్‌వైజ్ AI",
    login: "లాగిన్",
    logout: "లాగౌట్",
    language: "భాష",
    aiBadge: "AI-ఆధారిత వ్యవసాయం",
    heroTitle: "స్మార్ట్ వ్యవసాయం ఇక్కడ ప్రారంభమవుతుంది",
    heroSubtitle: "మీ మట్టి, వాతావరణం మరియు వనరులకు అనుగుణంగా AI-ఆధారిత పంట సిఫార్సులను పొందండి",
    getStarted: "ప్రారంభించండి",
    learnMore: "మరింత తెలుసుకోండి",
    cropTypes: "పంట రకాలు",
    accuracy: "ఖచ్చితత్వం",
    farmers: "రైతులు",
    formTitle: "మీ పొలం గురించి చెప్పండి",
    formSubtitle: "వ్యక్తిగత పంట సిఫార్సుల కోసం మీ పొలం వివరాలను నమోదు చేయండి",
    soilType: "మట్టి రకం",
    selectSoilType: "మట్టి రకాన్ని ఎంచుకోండి",
    climate: "వాతావరణం",
    selectClimate: "వాతావరణాన్ని ఎంచుకోండి",
    waterAvailability: "నీటి లభ్యత",
    selectWaterAvailability: "నీటి లభ్యతను ఎంచుకోండి",
    farmSize: "పొలం పరిమాణం (ఎకరాలు)",
    enterFarmSize: "పొలం పరిమాణాన్ని నమోదు చేయండి",
    season: "పెరుగుదల సీజన్",
    selectSeason: "సీజన్‌ను ఎంచుకోండి",
    getRecommendations: "పంట సిఫార్సులను పొందండి",
    analyzing: "విశ్లేషిస్తోంది...",
    orUploadImage: "లేదా ఫోటో అప్‌లోడ్ చేయండి",
    uploadImageDesc: "AI సిఫార్సుల కోసం మీ మట్టి, వాతావరణం లేదా పంట ఫోటో అప్‌లోడ్ చేయండి",
    uploadPhoto: "ఫోటో అప్‌లోడ్ చేయండి",
    analyzeImage: "చిత్రాన్ని విశ్లేషించండి",
    analyzingImage: "విశ్లేషిస్తోంది...",
    clay: "బంకమట్టి",
    sandy: "ఇసుక మట్టి",
    loamy: "సారవంతమైన మట్టి",
    silt: "సిల్ట్ మట్టి",
    peat: "పీట్ మట్టి",
    chalky: "సుద్ద మట్టి",
    tropical: "ఉష్ణమండల",
    subtropical: "ఉప ఉష్ణమండల",
    temperate: "సమశీతోష్ణ",
    arid: "శుష్క",
    semiarid: "అర్ధ-శుష్క",
    abundant: "సమృద్ధిగా (నీటిపారుదల)",
    moderate: "మధ్యస్థం (కాలానుగుణ వర్షం)",
    limited: "పరిమితం (పొడి ప్రాంతం)",
    rainfed: "వర్షాధారం మాత్రమే",
    kharif: "ఖరీఫ్ (వర్షాకాలం)",
    rabi: "రబీ (శీతాకాలం)",
    zaid: "జాయిద్ (వేసవి)",
    yearround: "ఏడాది పొడవునా",
    recommendedCrops: "మీ సిఫార్సు చేసిన పంటలు",
    basedOnConditions: "మీ పొలం పరిస్థితుల ఆధారంగా, ఉత్తమ పెరుగుదల మరియు దిగుబడి కోసం మా AI ఈ పంటలను సిఫార్సు చేస్తుంది.",
    tryDifferent: "వేరే పరిస్థితులు ప్రయత్నించండి",
    downloadReport: "రిపోర్ట్ డౌన్‌లోడ్ చేయండి",
    water: "నీరు",
    sunlight: "సూర్యకాంతి",
    growth: "పెరుగుదల",
    yield: "దిగుబడి",
    growingTips: "పెంపకం చిట్కాలు",
    match: "సరిపోలిక",
    rice: "వరి",
    wheat: "గోధుమ",
    corn: "మొక్కజొన్న",
    soybean: "సోయాబీన్",
    cotton: "పత్తి",
    millet: "సజ్జ",
    potatoes: "బంగాళాదుంప",
    tomatoes: "టమాటా",
    sorghum: "జొన్న",
    sugarcane: "చెరకు",
    // Water levels
    waterLow: "తక్కువ",
    waterMedium: "మధ్యస్థం",
    waterHigh: "ఎక్కువ",
    // Sunlight levels
    fullSun: "పూర్తి సూర్యకాంతి",
    partialShade: "పాక్షిక నీడ",
    shadeTolerant: "నీడ తట్టుకునే",
    // Yield levels
    yieldLow: "తక్కువ",
    yieldMedium: "మధ్యస్థం",
    yieldHigh: "ఎక్కువ",
    // Crop descriptions
    riceDesc: "నీరు నిలిచే పరిస్థితులలో బాగా పెరిగే ప్రధాన ధాన్యం పంట. సమృద్ధిగా నీరు ఉన్న ఉష్ణమండల వాతావరణానికి అనువైనది.",
    wheatDesc: "మధ్యస్థ నీటి లభ్యతతో సమశీతోష్ణ వాతావరణంలో బాగా పనిచేసే చల్లని కాలం ధాన్యం పంట.",
    cornDesc: "మధ్యస్థ నుండి మంచి నీటి సరఫరాతో వెచ్చని వాతావరణానికి తగిన బహుముఖ పంట.",
    soybeanDesc: "మట్టిని సారవంతం చేసే నైట్రోజన్-ఫిక్సింగ్ పప్పుధాన్యం. మంచి డ్రెయినేజ్ ఉన్న సారవంతమైన మట్టిలో పెరుగుతుంది.",
    cottonDesc: "వెచ్చని, అర్ధ-శుష్క పరిస్థితులలో పెరిగే ఫైబర్ పంట. వివిధ మట్టి రకాలను తట్టుకుంటుంది.",
    milletDesc: "పరిమిత నీటితో శుష్క ప్రాంతాలకు అనువైన కరువు-తట్టుకునే ధాన్యం.",
    potatoesDesc: "వదులుగా ఉన్న, మంచి డ్రెయినేజ్ ఉన్న సారవంతమైన మట్టితో చల్లని వాతావరణంలో అద్భుతంగా పనిచేసే దుంప పంట.",
    tomatoesDesc: "స్థిరమైన నీరు మరియు పోషకాలు అవసరమైన వెచ్చని కాలం కూరగాయ.",
    sorghumDesc: "వేడి, శుష్క వాతావరణానికి అనువైన కరువు-నిరోధక ధాన్యం. ధాన్యం, మేత మరియు జీవ ఇంధనం కోసం బహుముఖ పంట.",
    sugarcaneDesc: "సమృద్ధిగా నీరు మరియు సూర్యకాంతి అవసరమైన ఉష్ణమండల గడ్డి పంట.",
    // Crop tips
    riceTip1: "వృద్ధి సమయంలో 2-5 సెంమీ నిలిచే నీరు నిర్వహించండి",
    riceTip2: "నైట్రోజన్ ఎరువును విభజిత మోతాదులలో వేయండి",
    riceTip3: "తేమగా ఉన్న పరిస్థితులలో బ్లాస్ట్ వ్యాధిని పర్యవేక్షించండి",
    wheatTip1: "మట్టి ఉష్ణోగ్రత 10-15°C మధ్య ఉన్నప్పుడు విత్తండి",
    wheatTip2: "వేరు కుళ్ళిపోకుండా మంచి డ్రెయినేజ్ నిర్ధారించండి",
    wheatTip3: "బలమైన వేరు అభివృద్ధికి విత్తేటప్పుడు ఫాస్ఫరస్ వేయండి",
    cornTip1: "మట్టి ఉష్ణోగ్రత 16°C చేరినప్పుడు విత్తండి",
    cornTip2: "మొక్కలను 20-30 సెంమీ దూరంలో నాటండి",
    cornTip3: "టాసలింగ్ మరియు సిల్కింగ్ దశల్లో నీటిపారుదల కీలకం",
    soybeanTip1: "నైట్రోజన్ స్థిరీకరణకు విత్తనాలను రైజోబియంతో చికిత్స చేయండి",
    soybeanTip2: "పూసే సమయంలో నీరు నిలిచిపోకుండా చూడండి",
    soybeanTip3: "మట్టి ఆరోగ్యం కోసం ధాన్యాలతో పంట మార్పిడి చేయండి",
    cottonTip1: "180+ రోజుల మంచు లేని పెరుగుదల కాలం అవసరం",
    cottonTip2: "బొల్వార్మ్ మరియు తెల్ల ఈగను పర్యవేక్షించండి",
    cottonTip3: "ఫైబర్ నాణ్యత మెరుగుపరచడానికి పొటాషియం వేయండి",
    milletTip1: "స్థిరపడిన తర్వాత అత్యంత కరువు తట్టుకుంటుంది",
    milletTip2: "కనీస ఎరువు అవసరం",
    milletTip3: "అత్యవసర మేత పంటగా పనిచేయగలదు",
    potatoesTip1: "మొక్కలు పెరుగుతున్నప్పుడు మట్టి అద్దండి",
    potatoesTip2: "ఆకుపచ్చగా మారకుండా దుంపలను కప్పి ఉంచండి",
    potatoesTip3: "మట్టి ద్వారా వచ్చే వ్యాధులను నివారించడానికి పంట మార్పిడి చేయండి",
    tomatoesTip1: "మంచి గాలి ప్రసరణకు మొక్కలకు ఊతం ఇవ్వండి",
    tomatoesTip2: "మట్టి తేమను నిర్వహించడానికి మల్చ్ చేయండి",
    tomatoesTip3: "పెద్ద పండ్లకు సక్కర్లను కత్తిరించండి",
    sorghumTip1: "లోతైన వేరు వ్యవస్థ కరువులో మనుగడ సాగించడానికి వీలు కల్పిస్తుంది",
    sorghumTip2: "రెండవ పంటకు రేటూన్ చేయవచ్చు",
    sorghumTip3: "పక్వత సమయంలో పక్షి నష్టాన్ని నియంత్రించండి",
    sugarcaneTip1: "150-200 సెంమీ వార్షిక వర్షపాతం లేదా నీటిపారుదల అవసరం",
    sugarcaneTip2: "చక్కెర కంటెంట్ గరిష్టంగా ఉన్నప్పుడు కోయండి",
    sugarcaneTip3: "రేటూన్ పంటలు నాటడం ఖర్చులను తగ్గిస్తాయి",
    soilAnalysisTitle: "మట్టి విశ్లేషణ",
    weatherAnalysisTitle: "వాతావరణ విశ్లేషణ",
    moisture: "తేమ",
    analysisComplete: "విశ్లేషణ పూర్తయింది!",
    footerText: "AI-ఆధారిత అంతర్దృష్టులతో రైతులను సాధికారత చేయడం",
    allRights: "అన్ని హక్కులు రిజర్వ్ చేయబడ్డాయి",
  },
  bn: {
    appName: "ক্রপওয়াইজ AI",
    login: "লগইন",
    logout: "লগআউট",
    language: "ভাষা",
    aiBadge: "AI-চালিত কৃষি",
    heroTitle: "স্মার্ট চাষ এখানে শুরু হয়",
    heroSubtitle: "আপনার মাটি, জলবায়ু এবং সম্পদ অনুযায়ী AI-চালিত ফসল সুপারিশ পান",
    getStarted: "শুরু করুন",
    learnMore: "আরও জানুন",
    cropTypes: "ফসলের ধরন",
    accuracy: "নির্ভুলতা",
    farmers: "কৃষক",
    formTitle: "আপনার খামার সম্পর্কে বলুন",
    formSubtitle: "ব্যক্তিগত ফসল সুপারিশের জন্য আপনার খামারের বিবরণ পূরণ করুন",
    soilType: "মাটির ধরন",
    selectSoilType: "মাটির ধরন নির্বাচন করুন",
    climate: "জলবায়ু",
    selectClimate: "জলবায়ু নির্বাচন করুন",
    waterAvailability: "জলের প্রাপ্যতা",
    selectWaterAvailability: "জলের প্রাপ্যতা নির্বাচন করুন",
    farmSize: "খামারের আকার (একর)",
    enterFarmSize: "খামারের আকার লিখুন",
    season: "চাষের মৌসুম",
    selectSeason: "মৌসুম নির্বাচন করুন",
    getRecommendations: "ফসল সুপারিশ পান",
    analyzing: "বিশ্লেষণ হচ্ছে...",
    orUploadImage: "অথবা ফটো আপলোড করুন",
    uploadImageDesc: "AI সুপারিশের জন্য আপনার মাটি, আবহাওয়া বা ফসলের ফটো আপলোড করুন",
    uploadPhoto: "ফটো আপলোড করুন",
    analyzeImage: "ছবি বিশ্লেষণ করুন",
    analyzingImage: "বিশ্লেষণ হচ্ছে...",
    clay: "এঁটেল মাটি",
    sandy: "বালু মাটি",
    loamy: "দো-আঁশ মাটি",
    silt: "পলি মাটি",
    peat: "পিট মাটি",
    chalky: "চুন মাটি",
    tropical: "ক্রান্তীয়",
    subtropical: "উপক্রান্তীয়",
    temperate: "সমশীতোষ্ণ",
    arid: "শুষ্ক",
    semiarid: "আধা-শুষ্ক",
    abundant: "প্রচুর (সেচ)",
    moderate: "মাঝারি (মৌসুমী বৃষ্টি)",
    limited: "সীমিত (শুষ্ক অঞ্চল)",
    rainfed: "শুধু বৃষ্টিনির্ভর",
    kharif: "খরিফ (বর্ষা)",
    rabi: "রবি (শীতকাল)",
    zaid: "জায়েদ (গ্রীষ্মকাল)",
    yearround: "সারা বছর",
    recommendedCrops: "আপনার সুপারিশকৃত ফসল",
    basedOnConditions: "আপনার খামারের অবস্থার উপর ভিত্তি করে, সর্বোত্তম বৃদ্ধি এবং ফলনের জন্য আমাদের AI এই ফসলগুলি সুপারিশ করে।",
    tryDifferent: "ভিন্ন অবস্থা চেষ্টা করুন",
    downloadReport: "রিপোর্ট ডাউনলোড করুন",
    water: "জল",
    sunlight: "সূর্যালোক",
    growth: "বৃদ্ধি",
    yield: "ফলন",
    growingTips: "চাষের টিপস",
    match: "মিল",
    rice: "ধান",
    wheat: "গম",
    corn: "ভুট্টা",
    soybean: "সয়াবিন",
    cotton: "তুলা",
    millet: "বাজরা",
    potatoes: "আলু",
    tomatoes: "টমেটো",
    sorghum: "জোয়ার",
    sugarcane: "আখ",
    // Water levels
    waterLow: "কম",
    waterMedium: "মাঝারি",
    waterHigh: "বেশি",
    // Sunlight levels
    fullSun: "পূর্ণ সূর্যালোক",
    partialShade: "আংশিক ছায়া",
    shadeTolerant: "ছায়া সহনশীল",
    // Yield levels
    yieldLow: "কম",
    yieldMedium: "মাঝারি",
    yieldHigh: "বেশি",
    // Crop descriptions
    riceDesc: "একটি প্রধান শস্য ফসল যা জলাবদ্ধ অবস্থায় ভালো জন্মায়। প্রচুর জল সহ গ্রীষ্মমণ্ডলীয় জলবায়ুর জন্য আদর্শ।",
    wheatDesc: "একটি শীতল মৌসুমের শস্য ফসল যা মাঝারি জলের প্রাপ্যতা সহ সমশীতোষ্ণ জলবায়ুতে ভালো কার্যকর।",
    cornDesc: "মাঝারি থেকে ভালো জল সরবরাহ সহ উষ্ণ জলবায়ুর জন্য উপযুক্ত বহুমুখী ফসল।",
    soybeanDesc: "একটি নাইট্রোজেন-ফিক্সিং শিম ফসল যা মাটিকে সমৃদ্ধ করে। ভালো নিষ্কাশনযুক্ত দো-আঁশ মাটিতে জন্মায়।",
    cottonDesc: "উষ্ণ, আধা-শুষ্ক অবস্থায় জন্মানো ফাইবার ফসল। বিভিন্ন মাটির ধরন সহ্য করে।",
    milletDesc: "সীমিত জল সহ শুষ্ক অঞ্চলের জন্য খরা-সহনশীল শস্য।",
    potatoesDesc: "একটি কন্দ ফসল যা ঢিলে, ভালো নিষ্কাশনযুক্ত দো-আঁশ মাটি সহ শীতল জলবায়ুতে চমৎকার কার্যকর।",
    tomatoesDesc: "উষ্ণ মৌসুমের সবজি যার জন্য ধারাবাহিক জল এবং পুষ্টি প্রয়োজন।",
    sorghumDesc: "গরম, শুষ্ক জলবায়ুর জন্য উপযুক্ত খরা-প্রতিরোধী শস্য। শস্য, পশুখাদ্য এবং জৈব জ্বালানির জন্য বহুমুখী ফসল।",
    sugarcaneDesc: "গ্রীষ্মমণ্ডলীয় ঘাস ফসল যার জন্য প্রচুর জল এবং সূর্যালোক প্রয়োজন।",
    // Crop tips
    riceTip1: "বৃদ্ধির সময় 2-5 সেমি স্থির জল বজায় রাখুন",
    riceTip2: "নাইট্রোজেন সার বিভক্ত ডোজে দিন",
    riceTip3: "আর্দ্র অবস্থায় ব্লাস্ট রোগ পর্যবেক্ষণ করুন",
    wheatTip1: "মাটির তাপমাত্রা 10-15°C এর মধ্যে থাকলে বপন করুন",
    wheatTip2: "শিকড় পচা রোধ করতে ভালো নিষ্কাশন নিশ্চিত করুন",
    wheatTip3: "শক্তিশালী শিকড় বিকাশের জন্য বপনের সময় ফসফরাস দিন",
    cornTip1: "মাটির তাপমাত্রা 16°C পৌঁছালে বপন করুন",
    cornTip2: "গাছগুলি 20-30 সেমি দূরে রোপণ করুন",
    cornTip3: "ট্যাসেলিং এবং সিল্কিং পর্যায়ে সেচ গুরুত্বপূর্ণ",
    soybeanTip1: "নাইট্রোজেন স্থিরকরণের জন্য বীজগুলিকে রাইজোবিয়াম দিয়ে চিকিত্সা করুন",
    soybeanTip2: "ফুল ফোটার সময় জলাবদ্ধতা এড়িয়ে চলুন",
    soybeanTip3: "মাটির স্বাস্থ্যের জন্য শস্যের সাথে ফসল চক্র করুন",
    cottonTip1: "180+ দিনের হিম-মুক্ত বৃদ্ধির সময়কাল প্রয়োজন",
    cottonTip2: "বোলওয়ার্ম এবং সাদা মাছি পর্যবেক্ষণ করুন",
    cottonTip3: "ফাইবার গুণমান উন্নতির জন্য পটাসিয়াম দিন",
    milletTip1: "প্রতিষ্ঠিত হওয়ার পর অত্যন্ত খরা সহনশীল",
    milletTip2: "ন্যূনতম সারের প্রয়োজনীয়তা",
    milletTip3: "জরুরি পশুখাদ্য ফসল হিসেবে কাজ করতে পারে",
    potatoesTip1: "গাছ বাড়ার সাথে সাথে মাটি উঁচু করুন",
    potatoesTip2: "সবুজ হওয়া রোধ করতে কন্দগুলি ঢেকে রাখুন",
    potatoesTip3: "মাটি বাহিত রোগ প্রতিরোধে ফসল চক্র করুন",
    tomatoesTip1: "ভালো বায়ু সঞ্চালনের জন্য গাছগুলিকে ঠেকনা দিন",
    tomatoesTip2: "মাটির আর্দ্রতা বজায় রাখতে মালচ করুন",
    tomatoesTip3: "বড় ফলের জন্য সাকার্স ছাঁটাই করুন",
    sorghumTip1: "গভীর শিকড় ব্যবস্থা খরায় বেঁচে থাকতে সক্ষম করে",
    sorghumTip2: "দ্বিতীয় ফসলের জন্য রেটুন করা যায়",
    sorghumTip3: "পরিপক্কতার সময় পাখির ক্ষতি নিয়ন্ত্রণ করুন",
    sugarcaneTip1: "150-200 সেমি বার্ষিক বৃষ্টিপাত বা সেচ প্রয়োজন",
    sugarcaneTip2: "চিনির পরিমাণ সর্বোচ্চ হলে ফসল কাটুন",
    sugarcaneTip3: "রেটুন ফসল রোপণ খরচ কমায়",
    soilAnalysisTitle: "মাটি বিশ্লেষণ",
    weatherAnalysisTitle: "আবহাওয়া বিশ্লেষণ",
    moisture: "আর্দ্রতা",
    analysisComplete: "বিশ্লেষণ সম্পূর্ণ!",
    footerText: "AI-চালিত অন্তর্দৃষ্টি দিয়ে কৃষকদের ক্ষমতায়ন",
    allRights: "সমস্ত অধিকার সংরক্ষিত",
  },
  gu: {
    appName: "ક્રોપવાઈઝ AI",
    login: "લૉગિન",
    logout: "લૉગઆઉટ",
    language: "ભાષા",
    aiBadge: "AI-સંચાલિત ખેતી",
    heroTitle: "સ્માર્ટ ખેતી અહીંથી શરૂ થાય છે",
    heroSubtitle: "તમારી જમીન, આબોહવા અને સંસાધનો અનુસાર AI-સંચાલિત પાક ભલામણો મેળવો",
    getStarted: "શરૂ કરો",
    learnMore: "વધુ જાણો",
    cropTypes: "પાક પ્રકારો",
    accuracy: "ચોકસાઈ",
    farmers: "ખેડૂતો",
    formTitle: "તમારા ખેતર વિશે જણાવો",
    formSubtitle: "વ્યક્તિગત પાક ભલામણો માટે તમારા ખેતરની વિગતો ભરો",
    soilType: "જમીનનો પ્રકાર",
    selectSoilType: "જમીનનો પ્રકાર પસંદ કરો",
    climate: "આબોહવા",
    selectClimate: "આબોહવા પસંદ કરો",
    waterAvailability: "પાણીની ઉપલબ્ધતા",
    selectWaterAvailability: "પાણીની ઉપલબ્ધતા પસંદ કરો",
    farmSize: "ખેતરનું કદ (એકર)",
    enterFarmSize: "ખેતરનું કદ દાખલ કરો",
    season: "ઉગાડવાની મોસમ",
    selectSeason: "મોસમ પસંદ કરો",
    getRecommendations: "પાક ભલામણો મેળવો",
    analyzing: "વિશ્લેષણ થઈ રહ્યું છે...",
    orUploadImage: "અથવા ફોટો અપલોડ કરો",
    uploadImageDesc: "AI ભલામણો માટે તમારી જમીન, હવામાન અથવા પાકનો ફોટો અપલોડ કરો",
    uploadPhoto: "ફોટો અપલોડ કરો",
    analyzeImage: "છબી વિશ્લેષણ કરો",
    analyzingImage: "વિશ્લેષણ થઈ રહ્યું છે...",
    clay: "માટી",
    sandy: "રેતાળ જમીન",
    loamy: "ગોરાડુ જમીન",
    silt: "કાંપવાળી જમીન",
    peat: "પીટ જમીન",
    chalky: "ચૂનાની જમીન",
    tropical: "ઉષ્ણકટિબંધીય",
    subtropical: "ઉપ-ઉષ્ણકટિબંધીય",
    temperate: "સમશીતોષ્ણ",
    arid: "શુષ્ક",
    semiarid: "અર્ધ-શુષ્ક",
    abundant: "પુષ્કળ (સિંચાઈ)",
    moderate: "મધ્યમ (મોસમી વરસાદ)",
    limited: "મર્યાદિત (શુષ્ક વિસ્તાર)",
    rainfed: "માત્ર વરસાદ આધારિત",
    kharif: "ખરીફ (ચોમાસું)",
    rabi: "રવી (શિયાળો)",
    zaid: "ઝાયદ (ઉનાળો)",
    yearround: "આખું વર્ષ",
    recommendedCrops: "તમારા ભલામણ કરેલ પાક",
    basedOnConditions: "તમારા ખેતરની સ્થિતિના આધારે, શ્રેષ્ઠ વૃદ્ધિ અને ઉપજ માટે અમારું AI આ પાકોની ભલામણ કરે છે.",
    tryDifferent: "અલગ સ્થિતિ અજમાવો",
    downloadReport: "રિપોર્ટ ડાઉનલોડ કરો",
    water: "પાણી",
    sunlight: "સૂર્યપ્રકાશ",
    growth: "વૃદ્ધિ",
    yield: "ઉપજ",
    growingTips: "ઉગાડવાની ટિપ્સ",
    match: "મેળ",
    rice: "ચોખા",
    wheat: "ઘઉં",
    corn: "મકાઈ",
    soybean: "સોયાબીન",
    cotton: "કપાસ",
    millet: "બાજરી",
    potatoes: "બટાકા",
    tomatoes: "ટામેટા",
    sorghum: "જુવાર",
    sugarcane: "શેરડી",
    // Water levels
    waterLow: "ઓછું",
    waterMedium: "મધ્યમ",
    waterHigh: "વધુ",
    // Sunlight levels
    fullSun: "પૂર્ણ સૂર્યપ્રકાશ",
    partialShade: "આંશિક છાંયો",
    shadeTolerant: "છાંયો સહન કરે",
    // Yield levels
    yieldLow: "ઓછી",
    yieldMedium: "મધ્યમ",
    yieldHigh: "વધુ",
    // Crop descriptions
    riceDesc: "એક મુખ્ય અનાજ પાક જે પાણી ભરાયેલી સ્થિતિમાં સારી રીતે ઉગે છે. પુષ્કળ પાણી સાથે ઉષ્ણકટિબંધીય આબોહવા માટે આદર્શ.",
    wheatDesc: "ઠંડી મોસમનો અનાજ પાક જે મધ્યમ પાણીની ઉપલબ્ધતા સાથે સમશીતોષ્ણ આબોહવામાં સારો દેખાવ કરે છે.",
    cornDesc: "મધ્યમથી સારી પાણી પુરવઠા સાથે ગરમ આબોહવા માટે યોગ્ય બહુમુખી પાક.",
    soybeanDesc: "નાઈટ્રોજન-ફિક્સિંગ કઠોળ પાક જે જમીનને સમૃદ્ધ બનાવે છે. સારી નિકાલવાળી ગોરાડુ જમીનમાં ઉગે છે.",
    cottonDesc: "ફાઈબર પાક જે ગરમ, અર્ધ-શુષ્ક પરિસ્થિતિમાં ઉગે છે. વિવિધ જમીન પ્રકારો સહન કરે છે.",
    milletDesc: "મર્યાદિત પાણી સાથે શુષ્ક વિસ્તારો માટે દુષ્કાળ-સહનશીલ અનાજ.",
    potatoesDesc: "એક કંદ પાક જે છૂટી, સારી નિકાલવાળી ગોરાડુ જમીન સાથે ઠંડી આબોહવામાં ઉત્તમ દેખાવ કરે છે.",
    tomatoesDesc: "ગરમ મોસમની શાકભાજી જેને સતત પાણી અને પોષક તત્વોની જરૂર છે.",
    sorghumDesc: "ગરમ, શુષ્ક આબોહવા માટે દુષ્કાળ-પ્રતિરોધક અનાજ. અનાજ, ઘાસચારો અને જૈવ બળતણ માટે બહુમુખી પાક.",
    sugarcaneDesc: "ઉષ્ણકટિબંધીય ઘાસ પાક જેને પુષ્કળ પાણી અને સૂર્યપ્રકાશની જરૂર છે.",
    // Crop tips
    riceTip1: "વૃદ્ધિ દરમિયાન 2-5 સેમી ઊભું પાણી જાળવો",
    riceTip2: "નાઈટ્રોજન ખાતર વિભાજિત ડોઝમાં આપો",
    riceTip3: "ભેજવાળી પરિસ્થિતિમાં બ્લાસ્ટ રોગ પર નજર રાખો",
    wheatTip1: "જમીનનું તાપમાન 10-15°C વચ્ચે હોય ત્યારે વાવો",
    wheatTip2: "મૂળ સડવું અટકાવવા સારી નિકાલ સુનિશ્ચિત કરો",
    wheatTip3: "મજબૂત મૂળ વિકાસ માટે વાવણી સમયે ફોસ્ફરસ આપો",
    cornTip1: "જમીનનું તાપમાન 16°C પહોંચે ત્યારે વાવો",
    cornTip2: "છોડને 20-30 સેમી અંતરે રોપો",
    cornTip3: "ટેસલિંગ અને સિલ્કિંગ તબક્કામાં સિંચાઈ મહત્વપૂર્ણ છે",
    soybeanTip1: "નાઈટ્રોજન સ્થિરીકરણ માટે બીજને રાઈઝોબિયમથી સારવાર કરો",
    soybeanTip2: "ફૂલ આવે ત્યારે પાણી ભરાવું ટાળો",
    soybeanTip3: "જમીનના સ્વાસ્થ્ય માટે અનાજ સાથે પાક ફેરબદલ કરો",
    cottonTip1: "180+ દિવસનો હિમ-મુક્ત વૃદ્ધિ સમયગાળો જરૂરી છે",
    cottonTip2: "બોલવોર્મ અને સફેદ માખી પર નજર રાખો",
    cottonTip3: "ફાઈબર ગુણવત્તા સુધારવા પોટેશિયમ આપો",
    milletTip1: "સ્થાપિત થયા પછી અત્યંત દુષ્કાળ સહનશીલ",
    milletTip2: "ન્યૂનતમ ખાતરની જરૂરિયાત",
    milletTip3: "કટોકટી ઘાસચારા પાક તરીકે કામ કરી શકે છે",
    potatoesTip1: "છોડ વધે તેમ માટી ચઢાવો",
    potatoesTip2: "લીલા થવાથી બચાવવા કંદને ઢાંકી રાખો",
    potatoesTip3: "જમીન જન્ય રોગો અટકાવવા પાક ફેરબદલ કરો",
    tomatoesTip1: "સારા હવા પરિભ્રમણ માટે છોડને ટેકો આપો",
    tomatoesTip2: "જમીનની ભેજ જાળવવા મલ્ચ કરો",
    tomatoesTip3: "મોટા ફળો માટે સકર્સ કાપો",
    sorghumTip1: "ઊંડી મૂળ પ્રણાલી દુષ્કાળમાં ટકી રહેવા સક્ષમ બનાવે છે",
    sorghumTip2: "બીજી લણણી માટે રેટૂન કરી શકાય છે",
    sorghumTip3: "પરિપક્વતા સમયે પક્ષીઓનું નુકસાન નિયંત્રિત કરો",
    sugarcaneTip1: "150-200 સેમી વાર્ષિક વરસાદ અથવા સિંચાઈ જરૂરી છે",
    sugarcaneTip2: "ખાંડનું પ્રમાણ મહત્તમ હોય ત્યારે લણણી કરો",
    sugarcaneTip3: "રેટૂન પાક વાવણી ખર્ચ ઘટાડે છે",
    soilAnalysisTitle: "જમીન વિશ્લેષણ",
    weatherAnalysisTitle: "હવામાન વિશ્લેષણ",
    moisture: "ભેજ",
    analysisComplete: "વિશ્લેષણ પૂર્ણ!",
    footerText: "AI-સંચાલિત આંતરદૃષ્ટિ સાથે ખેડૂતોને સશક્ત બનાવવું",
    allRights: "સર્વ હક્કો અનામત",
  },
};

const languageNames: Record<Language, string> = {
  en: "English",
  hi: "हिंदी",
  pa: "ਪੰਜਾਬੀ",
  mr: "मराठी",
  ta: "தமிழ்",
  te: "తెలుగు",
  bn: "বাংলা",
  gu: "ગુજરાતી",
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app-language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export { languageNames, translations };