import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'hi' | 'pa' | 'mr' | 'ta' | 'te' | 'bn' | 'gu';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    appName: "CropWise AI",
    login: "Login",
    logout: "Logout",
    language: "Language",
    
    // Hero Section
    aiBadge: "AI-Powered Agriculture",
    heroTitle: "Smart Farming Starts Here",
    heroSubtitle: "Get AI-powered crop recommendations tailored to your soil, climate, and resources",
    getStarted: "Get Started",
    learnMore: "Learn More",
    cropTypes: "Crop Types",
    accuracy: "Accuracy",
    farmers: "Farmers",
    
    // Form
    formTitle: "Tell Us About Your Farm",
    formSubtitle: "Fill in your farm details to get personalized crop recommendations",
    soilType: "Soil Type",
    selectSoilType: "Select soil type",
    climate: "Climate",
    selectClimate: "Select climate",
    waterAvailability: "Water Availability",
    selectWaterAvailability: "Select water availability",
    farmSize: "Farm Size (acres)",
    enterFarmSize: "Enter farm size",
    season: "Growing Season",
    selectSeason: "Select season",
    getRecommendations: "Get Crop Recommendations",
    analyzing: "Analyzing...",
    
    // Image Upload
    orUploadImage: "Or Upload Photo",
    uploadImageDesc: "Upload photos of your soil, weather conditions, or crop to get AI recommendations",
    uploadPhoto: "Upload Photo",
    analyzeImage: "Analyze Image",
    analyzingImage: "Analyzing...",
    
    // Soil types
    clay: "Clay",
    sandy: "Sandy",
    loamy: "Loamy",
    silt: "Silt",
    peat: "Peat",
    chalky: "Chalky",
    
    // Climate
    tropical: "Tropical",
    subtropical: "Subtropical",
    temperate: "Temperate",
    arid: "Arid/Dry",
    semiarid: "Semi-Arid",
    
    // Water
    abundant: "Abundant (Irrigation)",
    moderate: "Moderate (Seasonal Rain)",
    limited: "Limited (Dry Region)",
    rainfed: "Rain-fed Only",
    
    // Seasons
    kharif: "Kharif (Monsoon)",
    rabi: "Rabi (Winter)",
    zaid: "Zaid (Summer)",
    yearround: "Year-round",
    
    // Results
    recommendedCrops: "Your Recommended Crops",
    basedOnConditions: "Based on your farm conditions, our AI recommends these crops for optimal growth and yield.",
    tryDifferent: "Try Different Conditions",
    downloadReport: "Download Report",
    
    // Crop Card
    water: "Water",
    sunlight: "Sunlight",
    growth: "Growth",
    yield: "Yield",
    growingTips: "Growing Tips",
    match: "Match",
    
    // Crop names
    rice: "Rice",
    wheat: "Wheat",
    corn: "Corn (Maize)",
    soybean: "Soybean",
    cotton: "Cotton",
    millet: "Millet",
    potatoes: "Potatoes",
    tomatoes: "Tomatoes",
    sorghum: "Sorghum",
    sugarcane: "Sugarcane",
    
    // Footer
    footerText: "Empowering farmers with AI-driven insights",
    allRights: "All rights reserved",
  },
  hi: {
    // Header
    appName: "क्रॉपवाइज AI",
    login: "लॉगिन",
    logout: "लॉगआउट",
    language: "भाषा",
    
    // Hero Section
    aiBadge: "AI-संचालित कृषि",
    heroTitle: "स्मार्ट खेती यहाँ से शुरू होती है",
    heroSubtitle: "अपनी मिट्टी, जलवायु और संसाधनों के अनुसार AI-संचालित फसल सिफारिशें प्राप्त करें",
    getStarted: "शुरू करें",
    learnMore: "और जानें",
    cropTypes: "फसल प्रकार",
    accuracy: "सटीकता",
    farmers: "किसान",
    
    // Form
    formTitle: "अपने खेत के बारे में बताएं",
    formSubtitle: "व्यक्तिगत फसल सिफारिशें पाने के लिए अपने खेत का विवरण भरें",
    soilType: "मिट्टी का प्रकार",
    selectSoilType: "मिट्टी का प्रकार चुनें",
    climate: "जलवायु",
    selectClimate: "जलवायु चुनें",
    waterAvailability: "पानी की उपलब्धता",
    selectWaterAvailability: "पानी की उपलब्धता चुनें",
    farmSize: "खेत का आकार (एकड़)",
    enterFarmSize: "खेत का आकार दर्ज करें",
    season: "उगाने का मौसम",
    selectSeason: "मौसम चुनें",
    getRecommendations: "फसल सिफारिशें प्राप्त करें",
    analyzing: "विश्लेषण हो रहा है...",
    
    // Image Upload
    orUploadImage: "या फोटो अपलोड करें",
    uploadImageDesc: "AI सिफारिशें पाने के लिए अपनी मिट्टी, मौसम की स्थिति या फसल की फोटो अपलोड करें",
    uploadPhoto: "फोटो अपलोड करें",
    analyzeImage: "चित्र विश्लेषण करें",
    analyzingImage: "विश्लेषण हो रहा है...",
    
    // Soil types
    clay: "चिकनी मिट्टी",
    sandy: "रेतीली मिट्टी",
    loamy: "दोमट मिट्टी",
    silt: "गाद मिट्टी",
    peat: "पीट मिट्टी",
    chalky: "चूना मिट्टी",
    
    // Climate
    tropical: "उष्णकटिबंधीय",
    subtropical: "उपोष्णकटिबंधीय",
    temperate: "समशीतोष्ण",
    arid: "शुष्क/सूखा",
    semiarid: "अर्ध-शुष्क",
    
    // Water
    abundant: "प्रचुर (सिंचाई)",
    moderate: "मध्यम (मौसमी बारिश)",
    limited: "सीमित (सूखा क्षेत्र)",
    rainfed: "केवल वर्षा आधारित",
    
    // Seasons
    kharif: "खरीफ (मानसून)",
    rabi: "रबी (सर्दी)",
    zaid: "जायद (गर्मी)",
    yearround: "साल भर",
    
    // Results
    recommendedCrops: "आपकी अनुशंसित फसलें",
    basedOnConditions: "आपके खेत की स्थिति के आधार पर, हमारा AI इष्टतम विकास और उपज के लिए इन फसलों की सिफारिश करता है।",
    tryDifferent: "अलग स्थिति आज़माएं",
    downloadReport: "रिपोर्ट डाउनलोड करें",
    
    // Crop Card
    water: "पानी",
    sunlight: "धूप",
    growth: "विकास",
    yield: "उपज",
    growingTips: "उगाने के सुझाव",
    match: "मिलान",
    
    // Crop names
    rice: "चावल",
    wheat: "गेहूं",
    corn: "मक्का",
    soybean: "सोयाबीन",
    cotton: "कपास",
    millet: "बाजरा",
    potatoes: "आलू",
    tomatoes: "टमाटर",
    sorghum: "ज्वार",
    sugarcane: "गन्ना",
    
    // Footer
    footerText: "AI-संचालित अंतर्दृष्टि के साथ किसानों को सशक्त बनाना",
    allRights: "सर्वाधिकार सुरक्षित",
  },
  pa: {
    appName: "ਕ੍ਰੌਪਵਾਈਜ਼ AI",
    login: "ਲੌਗਇਨ",
    logout: "ਲੌਗਆਊਟ",
    language: "ਭਾਸ਼ਾ",
    aiBadge: "AI-ਸੰਚਾਲਿਤ ਖੇਤੀ",
    heroTitle: "ਸਮਾਰਟ ਖੇਤੀ ਇੱਥੇ ਸ਼ੁਰੂ ਹੁੰਦੀ ਹੈ",
    heroSubtitle: "ਆਪਣੀ ਮਿੱਟੀ, ਮੌਸਮ ਅਤੇ ਸਰੋਤਾਂ ਦੇ ਅਨੁਸਾਰ AI-ਸੰਚਾਲਿਤ ਫਸਲ ਸਿਫਾਰਸ਼ਾਂ ਪ੍ਰਾਪਤ ਕਰੋ",
    getStarted: "ਸ਼ੁਰੂ ਕਰੋ",
    learnMore: "ਹੋਰ ਜਾਣੋ",
    cropTypes: "ਫਸਲ ਕਿਸਮਾਂ",
    accuracy: "ਸਹੀਤਾ",
    farmers: "ਕਿਸਾਨ",
    formTitle: "ਆਪਣੇ ਖੇਤ ਬਾਰੇ ਦੱਸੋ",
    formSubtitle: "ਨਿੱਜੀ ਫਸਲ ਸਿਫਾਰਸ਼ਾਂ ਲਈ ਆਪਣੇ ਖੇਤ ਦਾ ਵੇਰਵਾ ਭਰੋ",
    soilType: "ਮਿੱਟੀ ਦੀ ਕਿਸਮ",
    selectSoilType: "ਮਿੱਟੀ ਦੀ ਕਿਸਮ ਚੁਣੋ",
    climate: "ਮੌਸਮ",
    selectClimate: "ਮੌਸਮ ਚੁਣੋ",
    waterAvailability: "ਪਾਣੀ ਦੀ ਉਪਲਬਧਤਾ",
    selectWaterAvailability: "ਪਾਣੀ ਦੀ ਉਪਲਬਧਤਾ ਚੁਣੋ",
    farmSize: "ਖੇਤ ਦਾ ਆਕਾਰ (ਏਕੜ)",
    enterFarmSize: "ਖੇਤ ਦਾ ਆਕਾਰ ਦਰਜ ਕਰੋ",
    season: "ਉਗਾਉਣ ਦਾ ਮੌਸਮ",
    selectSeason: "ਮੌਸਮ ਚੁਣੋ",
    getRecommendations: "ਫਸਲ ਸਿਫਾਰਸ਼ਾਂ ਪ੍ਰਾਪਤ ਕਰੋ",
    analyzing: "ਵਿਸ਼ਲੇਸ਼ਣ ਹੋ ਰਿਹਾ ਹੈ...",
    orUploadImage: "ਜਾਂ ਫੋਟੋ ਅੱਪਲੋਡ ਕਰੋ",
    uploadImageDesc: "AI ਸਿਫਾਰਸ਼ਾਂ ਲਈ ਆਪਣੀ ਮਿੱਟੀ, ਮੌਸਮ ਜਾਂ ਫਸਲ ਦੀ ਫੋਟੋ ਅੱਪਲੋਡ ਕਰੋ",
    uploadPhoto: "ਫੋਟੋ ਅੱਪਲੋਡ ਕਰੋ",
    analyzeImage: "ਚਿੱਤਰ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ",
    analyzingImage: "ਵਿਸ਼ਲੇਸ਼ਣ ਹੋ ਰਿਹਾ ਹੈ...",
    clay: "ਚਿਕਨੀ ਮਿੱਟੀ",
    sandy: "ਰੇਤਲੀ ਮਿੱਟੀ",
    loamy: "ਦੋਮਟ ਮਿੱਟੀ",
    silt: "ਸਿਲਟ ਮਿੱਟੀ",
    peat: "ਪੀਟ ਮਿੱਟੀ",
    chalky: "ਚੂਨਾ ਮਿੱਟੀ",
    tropical: "ਗਰਮ",
    subtropical: "ਉਪ-ਗਰਮ",
    temperate: "ਸਮਸ਼ੀਤੋਸ਼ਣ",
    arid: "ਸੁੱਕਾ",
    semiarid: "ਅਰਧ-ਸੁੱਕਾ",
    abundant: "ਭਰਪੂਰ (ਸਿੰਚਾਈ)",
    moderate: "ਮੱਧਮ (ਮੌਸਮੀ ਬਾਰਸ਼)",
    limited: "ਸੀਮਿਤ (ਸੁੱਕਾ ਖੇਤਰ)",
    rainfed: "ਸਿਰਫ਼ ਬਾਰਸ਼ ਆਧਾਰਿਤ",
    kharif: "ਖਰੀਫ਼ (ਮੌਨਸੂਨ)",
    rabi: "ਰਬੀ (ਸਰਦੀ)",
    zaid: "ਜ਼ਾਇਦ (ਗਰਮੀ)",
    yearround: "ਸਾਲ ਭਰ",
    recommendedCrops: "ਤੁਹਾਡੀਆਂ ਸਿਫਾਰਸ਼ੀ ਫਸਲਾਂ",
    basedOnConditions: "ਤੁਹਾਡੇ ਖੇਤ ਦੀ ਸਥਿਤੀ ਦੇ ਆਧਾਰ ਤੇ, ਸਾਡਾ AI ਵਧੀਆ ਵਾਧੇ ਅਤੇ ਝਾੜ ਲਈ ਇਨ੍ਹਾਂ ਫਸਲਾਂ ਦੀ ਸਿਫਾਰਸ਼ ਕਰਦਾ ਹੈ।",
    tryDifferent: "ਵੱਖਰੀ ਸਥਿਤੀ ਅਜ਼ਮਾਓ",
    downloadReport: "ਰਿਪੋਰਟ ਡਾਊਨਲੋਡ ਕਰੋ",
    water: "ਪਾਣੀ",
    sunlight: "ਧੁੱਪ",
    growth: "ਵਿਕਾਸ",
    yield: "ਝਾੜ",
    growingTips: "ਉਗਾਉਣ ਦੇ ਸੁਝਾਅ",
    match: "ਮਿਲਾਨ",
    rice: "ਚੌਲ",
    wheat: "ਕਣਕ",
    corn: "ਮੱਕੀ",
    soybean: "ਸੋਇਆਬੀਨ",
    cotton: "ਕਪਾਹ",
    millet: "ਬਾਜਰਾ",
    potatoes: "ਆਲੂ",
    tomatoes: "ਟਮਾਟਰ",
    sorghum: "ਜਵਾਰ",
    sugarcane: "ਗੰਨਾ",
    footerText: "AI-ਸੰਚਾਲਿਤ ਜਾਣਕਾਰੀ ਨਾਲ ਕਿਸਾਨਾਂ ਨੂੰ ਸਸ਼ਕਤ ਬਣਾਉਣਾ",
    allRights: "ਸਾਰੇ ਹੱਕ ਰਾਖਵੇਂ ਹਨ",
  },
  mr: {
    appName: "क्रॉपवाइज AI",
    login: "लॉगिन",
    logout: "लॉगआउट",
    language: "भाषा",
    aiBadge: "AI-चालित शेती",
    heroTitle: "स्मार्ट शेती इथे सुरू होते",
    heroSubtitle: "तुमच्या माती, हवामान आणि संसाधनांनुसार AI-चालित पीक शिफारसी मिळवा",
    getStarted: "सुरू करा",
    learnMore: "अधिक जाणून घ्या",
    cropTypes: "पीक प्रकार",
    accuracy: "अचूकता",
    farmers: "शेतकरी",
    formTitle: "तुमच्या शेताबद्दल सांगा",
    formSubtitle: "वैयक्तिक पीक शिफारसींसाठी तुमच्या शेताचा तपशील भरा",
    soilType: "मातीचा प्रकार",
    selectSoilType: "मातीचा प्रकार निवडा",
    climate: "हवामान",
    selectClimate: "हवामान निवडा",
    waterAvailability: "पाण्याची उपलब्धता",
    selectWaterAvailability: "पाण्याची उपलब्धता निवडा",
    farmSize: "शेताचा आकार (एकर)",
    enterFarmSize: "शेताचा आकार प्रविष्ट करा",
    season: "वाढीचा हंगाम",
    selectSeason: "हंगाम निवडा",
    getRecommendations: "पीक शिफारसी मिळवा",
    analyzing: "विश्लेषण होत आहे...",
    orUploadImage: "किंवा फोटो अपलोड करा",
    uploadImageDesc: "AI शिफारसींसाठी तुमची माती, हवामान किंवा पीक फोटो अपलोड करा",
    uploadPhoto: "फोटो अपलोड करा",
    analyzeImage: "चित्र विश्लेषण करा",
    analyzingImage: "विश्लेषण होत आहे...",
    clay: "चिकणमाती",
    sandy: "वाळूमाती",
    loamy: "गाळमाती",
    silt: "सिल्ट माती",
    peat: "पीट माती",
    chalky: "चुनखडी माती",
    tropical: "उष्णकटिबंधीय",
    subtropical: "उपोष्णकटिबंधीय",
    temperate: "समशीतोष्ण",
    arid: "कोरडे",
    semiarid: "अर्ध-कोरडे",
    abundant: "भरपूर (सिंचन)",
    moderate: "मध्यम (हंगामी पाऊस)",
    limited: "मर्यादित (कोरडा प्रदेश)",
    rainfed: "फक्त पावसावर अवलंबून",
    kharif: "खरीप (मान्सून)",
    rabi: "रब्बी (हिवाळा)",
    zaid: "उन्हाळी",
    yearround: "वर्षभर",
    recommendedCrops: "तुमची शिफारस केलेली पिके",
    basedOnConditions: "तुमच्या शेताच्या परिस्थितीवर आधारित, आमचे AI सर्वोत्तम वाढ आणि उत्पादनासाठी या पिकांची शिफारस करते.",
    tryDifferent: "वेगळी परिस्थिती वापरून पहा",
    downloadReport: "अहवाल डाउनलोड करा",
    water: "पाणी",
    sunlight: "सूर्यप्रकाश",
    growth: "वाढ",
    yield: "उत्पादन",
    growingTips: "वाढीचे सुझाव",
    match: "मिळान",
    rice: "भात",
    wheat: "गहू",
    corn: "मका",
    soybean: "सोयाबीन",
    cotton: "कापूस",
    millet: "बाजरी",
    potatoes: "बटाटे",
    tomatoes: "टोमॅटो",
    sorghum: "ज्वारी",
    sugarcane: "ऊस",
    footerText: "AI-चालित अंतर्दृष्टीसह शेतकऱ्यांना सक्षम करणे",
    allRights: "सर्व हक्क राखीव",
  },
  ta: {
    appName: "கிராப்வைஸ் AI",
    login: "உள்நுழை",
    logout: "வெளியேறு",
    language: "மொழி",
    aiBadge: "AI-இயக்கப்படும் விவசாயம்",
    heroTitle: "ஸ்மார்ட் விவசாயம் இங்கே தொடங்குகிறது",
    heroSubtitle: "உங்கள் மண், காலநிலை மற்றும் வளங்களுக்கு ஏற்ப AI-இயக்கப்படும் பயிர் பரிந்துரைகளைப் பெறுங்கள்",
    getStarted: "தொடங்கு",
    learnMore: "மேலும் அறிக",
    cropTypes: "பயிர் வகைகள்",
    accuracy: "துல்லியம்",
    farmers: "விவசாயிகள்",
    formTitle: "உங்கள் பண்ணையைப் பற்றி சொல்லுங்கள்",
    formSubtitle: "தனிப்பயன் பயிர் பரிந்துரைகளுக்கு உங்கள் பண்ணை விவரங்களை நிரப்பவும்",
    soilType: "மண் வகை",
    selectSoilType: "மண் வகையைத் தேர்ந்தெடுக்கவும்",
    climate: "காலநிலை",
    selectClimate: "காலநிலையைத் தேர்ந்தெடுக்கவும்",
    waterAvailability: "நீர் கிடைக்கும் தன்மை",
    selectWaterAvailability: "நீர் கிடைக்கும் தன்மையைத் தேர்ந்தெடுக்கவும்",
    farmSize: "பண்ணை அளவு (ஏக்கர்)",
    enterFarmSize: "பண்ணை அளவை உள்ளிடவும்",
    season: "வளர்ப்பு பருவம்",
    selectSeason: "பருவத்தைத் தேர்ந்தெடுக்கவும்",
    getRecommendations: "பயிர் பரிந்துரைகளைப் பெறு",
    analyzing: "பகுப்பாய்வு செய்யப்படுகிறது...",
    orUploadImage: "அல்லது புகைப்படம் பதிவேற்றவும்",
    uploadImageDesc: "AI பரிந்துரைகளுக்கு உங்கள் மண், காலநிலை அல்லது பயிர் புகைப்படத்தை பதிவேற்றவும்",
    uploadPhoto: "புகைப்படம் பதிவேற்றவும்",
    analyzeImage: "படத்தை பகுப்பாய்வு செய்",
    analyzingImage: "பகுப்பாய்வு செய்யப்படுகிறது...",
    clay: "களிமண்",
    sandy: "மணல் மண்",
    loamy: "செழிப்பான மண்",
    silt: "வண்டல் மண்",
    peat: "பீட் மண்",
    chalky: "சுண்ணாம்பு மண்",
    tropical: "வெப்ப மண்டல",
    subtropical: "துணை வெப்ப மண்டல",
    temperate: "மிதமான",
    arid: "வறண்ட",
    semiarid: "அரை வறண்ட",
    abundant: "ஏராளமான (பாசன)",
    moderate: "மிதமான (பருவ மழை)",
    limited: "குறைவான (வறண்ட பகுதி)",
    rainfed: "மழை நீர் மட்டும்",
    kharif: "கரீஃப் (பருவமழை)",
    rabi: "ரபி (குளிர்காலம்)",
    zaid: "ஜாய்த் (கோடைக்காலம்)",
    yearround: "ஆண்டு முழுவதும்",
    recommendedCrops: "உங்கள் பரிந்துரைக்கப்பட்ட பயிர்கள்",
    basedOnConditions: "உங்கள் பண்ணை நிலைமைகளின் அடிப்படையில், சிறந்த வளர்ச்சி மற்றும் விளைச்சலுக்கு எங்கள் AI இந்த பயிர்களை பரிந்துரைக்கிறது.",
    tryDifferent: "வேறு நிலைமைகளை முயற்சிக்கவும்",
    downloadReport: "அறிக்கையைப் பதிவிறக்கு",
    water: "நீர்",
    sunlight: "சூரிய ஒளி",
    growth: "வளர்ச்சி",
    yield: "விளைச்சல்",
    growingTips: "வளர்ப்பு குறிப்புகள்",
    match: "பொருத்தம்",
    rice: "அரிசி",
    wheat: "கோதுமை",
    corn: "சோளம்",
    soybean: "சோயாபீன்",
    cotton: "பருத்தி",
    millet: "கம்பு",
    potatoes: "உருளைக்கிழங்கு",
    tomatoes: "தக்காளி",
    sorghum: "சோளம்",
    sugarcane: "கரும்பு",
    footerText: "AI-இயக்கப்படும் நுண்ணறிவுகளுடன் விவசாயிகளை மேம்படுத்துதல்",
    allRights: "அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை",
  },
  te: {
    appName: "క్రాప్‌వైజ్ AI",
    login: "లాగిన్",
    logout: "లాగౌట్",
    language: "భాష",
    aiBadge: "AI-ఆధారిత వ్యవసాయం",
    heroTitle: "స్మార్ట్ వ్యవసాయం ఇక్కడ ప్రారంభమవుతుంది",
    heroSubtitle: "మీ మట్టి, వాతావరణం మరియు వనరులకు అనుగుణంగా AI-ఆధారిత పంట సిఫార్సులను పొందండి",
    getStarted: "ప్రారంభించండి",
    learnMore: "మరింత తెలుసుకోండి",
    cropTypes: "పంట రకాలు",
    accuracy: "ఖచ్చితత్వం",
    farmers: "రైతులు",
    formTitle: "మీ పొలం గురించి చెప్పండి",
    formSubtitle: "వ్యక్తిగత పంట సిఫార్సుల కోసం మీ పొలం వివరాలను నమోదు చేయండి",
    soilType: "మట్టి రకం",
    selectSoilType: "మట్టి రకాన్ని ఎంచుకోండి",
    climate: "వాతావరణం",
    selectClimate: "వాతావరణాన్ని ఎంచుకోండి",
    waterAvailability: "నీటి లభ్యత",
    selectWaterAvailability: "నీటి లభ్యతను ఎంచుకోండి",
    farmSize: "పొలం పరిమాణం (ఎకరాలు)",
    enterFarmSize: "పొలం పరిమాణాన్ని నమోదు చేయండి",
    season: "పెరుగుదల సీజన్",
    selectSeason: "సీజన్‌ను ఎంచుకోండి",
    getRecommendations: "పంట సిఫార్సులను పొందండి",
    analyzing: "విశ్లేషిస్తోంది...",
    orUploadImage: "లేదా ఫోటో అప్‌లోడ్ చేయండి",
    uploadImageDesc: "AI సిఫార్సుల కోసం మీ మట్టి, వాతావరణం లేదా పంట ఫోటో అప్‌లోడ్ చేయండి",
    uploadPhoto: "ఫోటో అప్‌లోడ్ చేయండి",
    analyzeImage: "చిత్రాన్ని విశ్లేషించండి",
    analyzingImage: "విశ్లేషిస్తోంది...",
    clay: "బంకమట్టి",
    sandy: "ఇసుక మట్టి",
    loamy: "సారవంతమైన మట్టి",
    silt: "సిల్ట్ మట్టి",
    peat: "పీట్ మట్టి",
    chalky: "సుద్ద మట్టి",
    tropical: "ఉష్ణమండల",
    subtropical: "ఉప ఉష్ణమండల",
    temperate: "సమశీతోష్ణ",
    arid: "శుష్క",
    semiarid: "అర్ధ-శుష్క",
    abundant: "సమృద్ధిగా (నీటిపారుదల)",
    moderate: "మధ్యస్థం (కాలానుగుణ వర్షం)",
    limited: "పరిమితం (పొడి ప్రాంతం)",
    rainfed: "వర్షాధారం మాత్రమే",
    kharif: "ఖరీఫ్ (వర్షాకాలం)",
    rabi: "రబీ (శీతాకాలం)",
    zaid: "జాయిద్ (వేసవి)",
    yearround: "ఏడాది పొడవునా",
    recommendedCrops: "మీ సిఫార్సు చేసిన పంటలు",
    basedOnConditions: "మీ పొలం పరిస్థితుల ఆధారంగా, ఉత్తమ పెరుగుదల మరియు దిగుబడి కోసం మా AI ఈ పంటలను సిఫార్సు చేస్తుంది.",
    tryDifferent: "వేరే పరిస్థితులు ప్రయత్నించండి",
    downloadReport: "రిపోర్ట్ డౌన్‌లోడ్ చేయండి",
    water: "నీరు",
    sunlight: "సూర్యకాంతి",
    growth: "పెరుగుదల",
    yield: "దిగుబడి",
    growingTips: "పెంపకం చిట్కాలు",
    match: "సరిపోలిక",
    rice: "వరి",
    wheat: "గోధుమ",
    corn: "మొక్కజొన్న",
    soybean: "సోయాబీన్",
    cotton: "పత్తి",
    millet: "సజ్జ",
    potatoes: "బంగాళాదుంప",
    tomatoes: "టమాటా",
    sorghum: "జొన్న",
    sugarcane: "చెరకు",
    footerText: "AI-ఆధారిత అంతర్దృష్టులతో రైతులను సాధికారత చేయడం",
    allRights: "అన్ని హక్కులు రిజర్వ్ చేయబడ్డాయి",
  },
  bn: {
    appName: "ক্রপওয়াইজ AI",
    login: "লগইন",
    logout: "লগআউট",
    language: "ভাষা",
    aiBadge: "AI-চালিত কৃষি",
    heroTitle: "স্মার্ট চাষ এখানে শুরু হয়",
    heroSubtitle: "আপনার মাটি, জলবায়ু এবং সম্পদ অনুযায়ী AI-চালিত ফসল সুপারিশ পান",
    getStarted: "শুরু করুন",
    learnMore: "আরও জানুন",
    cropTypes: "ফসলের ধরন",
    accuracy: "নির্ভুলতা",
    farmers: "কৃষক",
    formTitle: "আপনার খামার সম্পর্কে বলুন",
    formSubtitle: "ব্যক্তিগত ফসল সুপারিশের জন্য আপনার খামারের বিবরণ পূরণ করুন",
    soilType: "মাটির ধরন",
    selectSoilType: "মাটির ধরন নির্বাচন করুন",
    climate: "জলবায়ু",
    selectClimate: "জলবায়ু নির্বাচন করুন",
    waterAvailability: "জলের প্রাপ্যতা",
    selectWaterAvailability: "জলের প্রাপ্যতা নির্বাচন করুন",
    farmSize: "খামারের আকার (একর)",
    enterFarmSize: "খামারের আকার লিখুন",
    season: "চাষের মৌসুম",
    selectSeason: "মৌসুম নির্বাচন করুন",
    getRecommendations: "ফসল সুপারিশ পান",
    analyzing: "বিশ্লেষণ হচ্ছে...",
    orUploadImage: "অথবা ফটো আপলোড করুন",
    uploadImageDesc: "AI সুপারিশের জন্য আপনার মাটি, আবহাওয়া বা ফসলের ফটো আপলোড করুন",
    uploadPhoto: "ফটো আপলোড করুন",
    analyzeImage: "ছবি বিশ্লেষণ করুন",
    analyzingImage: "বিশ্লেষণ হচ্ছে...",
    clay: "এঁটেল মাটি",
    sandy: "বালু মাটি",
    loamy: "দো-আঁশ মাটি",
    silt: "পলি মাটি",
    peat: "পিট মাটি",
    chalky: "চুন মাটি",
    tropical: "ক্রান্তীয়",
    subtropical: "উপক্রান্তীয়",
    temperate: "সমশীতোষ্ণ",
    arid: "শুষ্ক",
    semiarid: "আধা-শুষ্ক",
    abundant: "প্রচুর (সেচ)",
    moderate: "মাঝারি (মৌসুমী বৃষ্টি)",
    limited: "সীমিত (শুষ্ক অঞ্চল)",
    rainfed: "শুধু বৃষ্টিনির্ভর",
    kharif: "খরিফ (বর্ষা)",
    rabi: "রবি (শীতকাল)",
    zaid: "জায়েদ (গ্রীষ্মকাল)",
    yearround: "সারা বছর",
    recommendedCrops: "আপনার সুপারিশকৃত ফসল",
    basedOnConditions: "আপনার খামারের অবস্থার উপর ভিত্তি করে, সর্বোত্তম বৃদ্ধি এবং ফলনের জন্য আমাদের AI এই ফসলগুলি সুপারিশ করে।",
    tryDifferent: "ভিন্ন অবস্থা চেষ্টা করুন",
    downloadReport: "রিপোর্ট ডাউনলোড করুন",
    water: "জল",
    sunlight: "সূর্যালোক",
    growth: "বৃদ্ধি",
    yield: "ফলন",
    growingTips: "চাষের টিপস",
    match: "মিল",
    rice: "ধান",
    wheat: "গম",
    corn: "ভুট্টা",
    soybean: "সয়াবিন",
    cotton: "তুলা",
    millet: "বাজরা",
    potatoes: "আলু",
    tomatoes: "টমেটো",
    sorghum: "জোয়ার",
    sugarcane: "আখ",
    footerText: "AI-চালিত অন্তর্দৃষ্টি দিয়ে কৃষকদের ক্ষমতায়ন",
    allRights: "সমস্ত অধিকার সংরক্ষিত",
  },
  gu: {
    appName: "ક્રોપવાઈઝ AI",
    login: "લૉગિન",
    logout: "લૉગઆઉટ",
    language: "ભાષા",
    aiBadge: "AI-સંચાલિત ખેતી",
    heroTitle: "સ્માર્ટ ખેતી અહીંથી શરૂ થાય છે",
    heroSubtitle: "તમારી જમીન, આબોહવા અને સંસાધનો અનુસાર AI-સંચાલિત પાક ભલામણો મેળવો",
    getStarted: "શરૂ કરો",
    learnMore: "વધુ જાણો",
    cropTypes: "પાક પ્રકારો",
    accuracy: "ચોકસાઈ",
    farmers: "ખેડૂતો",
    formTitle: "તમારા ખેતર વિશે જણાવો",
    formSubtitle: "વ્યક્તિગત પાક ભલામણો માટે તમારા ખેતરની વિગતો ભરો",
    soilType: "જમીનનો પ્રકાર",
    selectSoilType: "જમીનનો પ્રકાર પસંદ કરો",
    climate: "આબોહવા",
    selectClimate: "આબોહવા પસંદ કરો",
    waterAvailability: "પાણીની ઉપલબ્ધતા",
    selectWaterAvailability: "પાણીની ઉપલબ્ધતા પસંદ કરો",
    farmSize: "ખેતરનું કદ (એકર)",
    enterFarmSize: "ખેતરનું કદ દાખલ કરો",
    season: "ઉગાડવાની મોસમ",
    selectSeason: "મોસમ પસંદ કરો",
    getRecommendations: "પાક ભલામણો મેળવો",
    analyzing: "વિશ્લેષણ થઈ રહ્યું છે...",
    orUploadImage: "અથવા ફોટો અપલોડ કરો",
    uploadImageDesc: "AI ભલામણો માટે તમારી જમીન, હવામાન અથવા પાકનો ફોટો અપલોડ કરો",
    uploadPhoto: "ફોટો અપલોડ કરો",
    analyzeImage: "છબી વિશ્લેષણ કરો",
    analyzingImage: "વિશ્લેષણ થઈ રહ્યું છે...",
    clay: "માટી",
    sandy: "રેતાળ જમીન",
    loamy: "ગોરાડુ જમીન",
    silt: "કાંપવાળી જમીન",
    peat: "પીટ જમીન",
    chalky: "ચૂનાની જમીન",
    tropical: "ઉષ્ણકટિબંધીય",
    subtropical: "ઉપ-ઉષ્ણકટિબંધીય",
    temperate: "સમશીતોષ્ણ",
    arid: "શુષ્ક",
    semiarid: "અર્ધ-શુષ્ક",
    abundant: "પુષ્કળ (સિંચાઈ)",
    moderate: "મધ્યમ (મોસમી વરસાદ)",
    limited: "મર્યાદિત (શુષ્ક વિસ્તાર)",
    rainfed: "માત્ર વરસાદ આધારિત",
    kharif: "ખરીફ (ચોમાસું)",
    rabi: "રવી (શિયાળો)",
    zaid: "ઝાયદ (ઉનાળો)",
    yearround: "આખું વર્ષ",
    recommendedCrops: "તમારા ભલામણ કરેલ પાક",
    basedOnConditions: "તમારા ખેતરની સ્થિતિના આધારે, શ્રેષ્ઠ વૃદ્ધિ અને ઉપજ માટે અમારું AI આ પાકોની ભલામણ કરે છે.",
    tryDifferent: "અલગ સ્થિતિ અજમાવો",
    downloadReport: "રિપોર્ટ ડાઉનલોડ કરો",
    water: "પાણી",
    sunlight: "સૂર્યપ્રકાશ",
    growth: "વૃદ્ધિ",
    yield: "ઉપજ",
    growingTips: "ઉગાડવાની ટિપ્સ",
    match: "મેળ",
    rice: "ચોખા",
    wheat: "ઘઉં",
    corn: "મકાઈ",
    soybean: "સોયાબીન",
    cotton: "કપાસ",
    millet: "બાજરી",
    potatoes: "બટાકા",
    tomatoes: "ટામેટા",
    sorghum: "જુવાર",
    sugarcane: "શેરડી",
    footerText: "AI-સંચાલિત આંતરદૃષ્ટિ સાથે ખેડૂતોને સશક્ત બનાવવું",
    allRights: "સર્વ હક્કો અનામત",
  },
};

const languageNames: Record<Language, string> = {
  en: "English",
  hi: "हिंदी",
  pa: "ਪੰਜਾਬੀ",
  mr: "मराठी",
  ta: "தமிழ்",
  te: "తెలుగు",
  bn: "বাংলা",
  gu: "ગુજરાતી",
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app-language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export { languageNames, translations };